packages:
  - 'packages/*'
  - 'apps/*'

nodeLinker: hoisted
shamefullyHoist: true

verifyDepsBeforeRun: false

allowBuilds:
  '@swc/core': false
  electron: true
  electron-winstaller: true
  esbuild: true
  lefthook: true
  msw: true

catalog:
  '@vitest/coverage-v8': ^5.0.1
  esbuild: ^0.28.2
  i18next: ^26.4.2
  react: ^19.3.0
  react-dom: ^19.3.0
  rimraf: ^6.1.3
  typescript: ^7.0.2
  vitest: ^5.0.1
  zod: ^4.6.5

blockExoticSubdeps: true
minimumReleaseAge: 1440
