export enum IpcKey {
  CONVERT_START = 'startConversion',
  CONVERT_STATUS = 'conversionStatus',
  CONVERT_CANCEL = 'cancelConversion',
  SCAN_START = 'startScan',
  SELECT_FOLDER_START = 'startSelectFolder',
  SELECT_FOLDER_RESULT = 'folderSelected',
  SELECT_OUTPUT_START = 'startSelectOutput',
  SELECT_OUTPUT_RESULT = 'outputSelected',
  SELECT_GAME_START = 'startSelectGame',
  SELECT_GAME_RESULT = 'gameSelected',
  OPEN_FOLDER = 'openFolder',
  TEST_PROVIDER = 'testProvider',
  TEST_PROVIDER_RESULT = 'testProviderResult'
}

/** What the worker was asked to do */
export enum WorkerAction {
  SCAN = 'scan',
  CONVERT = 'convert'
}

export enum TranslateProvider {
  OLLAMA = 'ollama',
  OPENAI = 'openai'
}

/** Everything the translation engine needs, all of it user editable */
export interface TranslateConfig {
  enabled: boolean
  provider: TranslateProvider
  baseUrl: string
  model: string
  apiKey?: string
  /** Strings sent per request */
  batchSize: number
  /** Requests in flight at once */
  concurrency: number
  /** Attempts before a batch is split */
  retries: number
  /** Per request timeout in milliseconds */
  timeout: number
  /** What the game is about, filled in by the worker from the selected game */
  domain?: string
  /** Game installation folder, its own localisation is the best glossary there is */
  gamePath?: string
}

export enum ConversionStatusType {
  LOG,
  STATUS,
  PROGRESS
}

export enum ConversionLogMessage {
  STARTING = 'conversionLog.starting',
  DONE = 'conversionLog.done',
  SINGLE_MOD = 'conversionLog.singleMod',
  MODS_FOUND = 'conversionLog.modsFound',
  SUMMARY = 'conversionLog.summary',
  MOD_CREATED = 'conversionLog.modCreated',
  TRANSLATING = 'conversionLog.translating',
  GLOSSARY = 'conversionLog.glossary',
  CANCELLED = 'conversionLog.cancelled'
}

export enum ConversionStatus {
  WAITING,
  STARTED,
  SCANNING_FILES,
  COMPARING_FILES,
  WAITING_USER_INPUT,
  CREATING_FILES,
  FINISHED,
  ERROR,
  PROCESSING_MODS,
  SCAN_FINISHED,
  CANCELLED
}

export enum ConvertMode {
  ADD_TO_CURRENT = 0,
  EXTRACT_TO_FOLDER = 1,
  CREATE_TRANSLATION_MOD = 2
}

/** Values passed to i18next for interpolation in a log line */
export type LogValues = Record<string, string | number>

export interface ConversionLog {
  type: ConversionStatusType.LOG
  ts: number
  message: string
  values?: LogValues
}

/** Emitted once per finished mod so the UI can show a real progress bar */
export interface ConversionProgress {
  type: ConversionStatusType.PROGRESS
  current: number
  total: number
  modName: string
  /** Set while translating, counts strings rather than mods */
  translation?: TranslationCounters
}

// A type alias, not an interface: i18next needs an implicit index signature to interpolate it
export type TranslationCounters = {
  translated: number
  cached: number
  failed: number
}

/** One mod as reported by a scan, before anything is written */
export interface ScannedMod {
  id: string
  name: string
  path: string
  localisationFiles: number
  sourceFiles: number
  /** Missing files per target language */
  missing: Record<string, number>
  /** Total keys the source language declares */
  sourceKeys: number
  /** A localisation folder spelled the other way exists here: wrong game selected */
  otherSpelling?: boolean
  /** Keys still untranslated, per target language */
  missingKeys: Record<string, number>
  missingFiles: number
  /** Translatable lines inside the missing files, drives the time estimate */
  missingLines: number
  supportedVersion?: string
  errors: string[]
}

export interface ScanOutput {
  mods: ScannedMod[]
  totals: {
    mods: number
    missingFiles: number
    missingLines: number
    /** Mods holding no localisation folder for the selected game */
    withoutLocalisation: number
    /** Mods where the other spelling was found instead */
    otherSpelling: number
  }
}

/** Result of a single mod folder */
export interface ModResult {
  /** Folder name (workshop id for subscribed mods) */
  id: string
  /** Human readable name read from descriptor.mod, falls back to the folder name */
  name: string
  path: string
  localisationFiles: number
  sourceFiles: number
  createdCount: number
  skippedCount: number
  failedCount: number
  /** Sample of created files per language, capped to keep the IPC payload usable */
  created: Record<string, string[]>
  /** How many created files were left out of `created` */
  truncated: number
  /** supported_version declared by the mod, reused for the generated translation mod */
  supportedVersion?: string
  errors: string[]
}

/** The mod generated by ConvertMode.CREATE_TRANSLATION_MOD */
export interface TranslationMod {
  /** Name shown in the game launcher */
  name: string
  /** Folder name below the game mod directory */
  folder: string
  /** Absolute path of the mod folder */
  path: string
  supportedVersion: string
}

export interface ConversionOutput {
  mods: ModResult[]
  translationMod?: TranslationMod
  translation?: TranslationCounters
  cancelled?: boolean
  totals: {
    mods: number
    modsWithFiles: number
    created: number
    skipped: number
    failed: number
    errors: number
  }
}
