// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "hOVQPOOOOQO'#C`'#C`QVQPOOOOQO-E6^-E6^",
  stateData: "_~OVOS~OQPORPO~O",
  goto: "[TPPPPUQQORRQ",
  nodeNames: "⚠ TextFile Property Punctuation",
  maxTerm: 7,
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "#c~R`X^!Tpq!T!O!P!x!Q![!x![!]#^!c!}!x#R#S!x#T#o!x#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!YYV~X^!Tpq!T#y#z!T$f$g!T#BY#BZ!T$IS$I_!T$I|$JO!T$JT$JU!T$KV$KW!T&FU&FV!T~!}TQ~!O!P!x!Q![!x!c!}!x#R#S!x#T#o!x~#cOR~",
  tokenizers: [0],
  topRules: {"TextFile":[0,1]},
  tokenPrec: 0
})
