import * as fs from 'fs/promises'
import type { Dirent } from 'fs'
import * as path from 'path'
import { GAMES, LANGUAGES } from '../../global/constants'
import {
  ConversionLogMessage,
  ConversionOutput,
  ConversionStatus,
  ConversionStatusType,
  ConvertMode,
  LogValues,
  ModResult,
  ScannedMod,
  ScanOutput,
  TranslateConfig,
  TranslationMod,
  WorkerAction
} from '../../global/types'
import { TranslationEngine } from '../translate/engine'
import { Glossary, loadGlossary } from '../translate/glossary'
import { TranslationMemory } from '../translate/memory'
import { entryKey, isTranslatable, parseLocFile, serializeLocFile } from '../translate/yml'

export interface Request {
  action?: WorkerAction
  path: string
  game: string
  sourceLanguage: string
  targetLanguages: string[]
  mode: ConvertMode
  outputPath?: string
  /** Name of the mod generated by ConvertMode.CREATE_TRANSLATION_MOD */
  modName?: string
  /** Documents folder, resolved by the main process since Electron is not available here */
  documentsPath?: string
  /** Folder holding the translation memory, also resolved by the main process */
  userDataPath?: string
  /** Mod folder names to process, every discovered mod when left out */
  selectedMods?: string[]
  translate?: TranslateConfig
}

/** How many mods are scanned at the same time */
const MOD_CONCURRENCY = 8

/** Share of a localisation mod key set that must land on one mod to call it a patch of it */
const KEY_OVERLAP_MATCH = 0.5

/** How many created files are reported per mod, the rest is only counted */
const MAX_LISTED_FILES_PER_MOD = 100

/**
 * Suffix for a generated file that sits next to an existing translation.
 * Topping up an existing file would mean rewriting someone else's work, so the missing
 * keys go into a file of their own instead.
 */
const PARTIAL_SUFFIX = '_ptt_missing'

/** Fallbacks when the user leaves the translation mod name empty */
const DEFAULT_MOD_NAME = 'Missing Translations'
const DEFAULT_MOD_FOLDER = 'missing_translations'

/** A .yml file located inside a localisation folder */
interface LocalisationFile {
  path: string
  /** Index of the localisation segment in the splitted path */
  locIndex: number
  /** Path segments after the localisation folder, last one being the file name */
  rest: string[]
}

interface ModFolder {
  id: string
  path: string
}

interface CreationJob {
  source: string
  target: string
  /** Path below the language folder, used when packing into a translation mod */
  packed: string[]
  /** Only these keys go into the target file, everything else is already translated */
  keys: Set<string>
}

interface Descriptor {
  name?: string
  supportedVersion?: string
  remoteFileId?: string
  dependencies?: string[]
}

interface LocalisationEntry {
  key: string
  file: string
  described: LocalisationFile
  language: string
}

interface Coverage {
  byLanguage: Map<string, Set<string>>
  /** Names of the mods providing the coverage, shown so the user can see who covers what */
  sources: string[]
}

interface ModKeys {
  files: number
  /** Language to key to where that key was declared */
  byLanguage: Map<string, Map<string, LocalisationEntry>>
}

/** Split a path on both separators so the logic is not Windows only */
const splitPath = (value: string): string[] => value.split(/[\\/]+/)

/** Comparable form of a path: same separator, same case */
const pathKey = (value: string): string => value.replace(/[\\/]+/g, '/').toLowerCase()

/**
 * Run an async task over a list, a few items at a time
 * @param items - The items to process
 * @param limit - Maximum number of tasks running at once
 * @param task - The task to run
 * @returns The results, in the order of `items`
 */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  task: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length)
  let cursor = 0

  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) {
      const index = cursor++
      if (index >= items.length) return
      results[index] = await task(items[index], index)
    }
  })

  await Promise.all(runners)
  return results
}

/**
 * Recursively list all .yml translation files of a mod
 * A file counts only if one of its parent folders is the game's localisation folder
 * @param dirPath - The directory path to search
 * @param translateKey - The game's folder translate key
 * @param inLocalisation - True once we are below the localisation folder
 * @param errors - Collects unreadable folders instead of throwing
 * @returns Array of .yml file paths
 */
async function listTradFiles(
  dirPath: string,
  translateKey: string,
  inLocalisation: boolean,
  errors: string[],
  notes?: { otherSpelling: boolean }
): Promise<string[]> {
  let items: Dirent[]
  try {
    items = await fs.readdir(dirPath, { withFileTypes: true })
  } catch (error) {
    errors.push(`${dirPath} : ${(error as Error).message}`)
    return []
  }

  const ymlFiles: string[] = []
  const subDirectories: Promise<string[]>[] = []

  for (const item of items) {
    const fullPath = path.join(dirPath, item.name)
    const name = item.name.toLowerCase()

    if (item.isDirectory()) {
      // The two spellings are a classic mix-up: CK3 says localization, the others localisation
      if (notes && name !== translateKey && (name === 'localisation' || name === 'localization')) {
        notes.otherSpelling = true
      }
      // replace/ used to be skipped; real mods keep translated strings there, so it counts
      subDirectories.push(
        listTradFiles(
          fullPath,
          translateKey,
          inLocalisation || name === translateKey,
          errors,
          notes
        )
      )
    } else if (inLocalisation && item.isFile() && name.endsWith('.yml')) {
      ymlFiles.push(fullPath)
    }
  }

  const nested = await Promise.all(subDirectories)
  return ymlFiles.concat(...nested)
}

/**
 * Describe a localisation file relative to its localisation folder
 * @param filePath - The file path
 * @param translateKey - The game's folder translate key
 * @returns The described file, or null if it is not below a localisation folder
 */
const parseLocalisationFile = (filePath: string, translateKey: string): LocalisationFile | null => {
  const segments = splitPath(filePath)
  // Deepest localisation folder wins, a mod can nest one inside another folder
  const locIndex = segments.map((segment) => segment.toLowerCase()).lastIndexOf(translateKey)
  if (locIndex === -1 || locIndex === segments.length - 1) return null
  return { path: filePath, locIndex, rest: segments.slice(locIndex + 1) }
}

/**
 * Build the path a file would have in the target language
 * Only the segments below the localisation folder are rewritten, so a mod folder
 * named after a language (english_names_fix, ...) is never mangled
 * @param file - The described source file
 * @param sourceLanguage - The source language key
 * @param targetLanguage - The target language key
 * @returns The target file path
 */
const getTargetFile = (
  file: LocalisationFile,
  sourceLanguage: string,
  targetLanguage: string
): string => {
  const segments = splitPath(file.path)
  const head = segments.slice(0, file.locIndex + 1)
  const lastIndex = file.rest.length - 1

  const tail = file.rest.map((segment, index) => {
    // The file name carries the language tag (foo_l_english.yml), rewrite every occurrence
    if (index === lastIndex) return segment.replaceAll(sourceLanguage, targetLanguage)
    // A folder is renamed only when it *is* the language, never on a partial match
    return segment.toLowerCase() === sourceLanguage ? targetLanguage : segment
  })

  return [...head, ...tail].join(path.sep)
}

/**
 * Read what we need from a mod descriptor
 * @param modPath - The mod folder
 * @returns The declared name and supported version, both optional
 */
const readDescriptor = async (modPath: string): Promise<Descriptor> => {
  let descriptors: string[]
  try {
    const items = await fs.readdir(modPath, { withFileTypes: true })
    descriptors = items
      .filter((item) => item.isFile() && item.name.toLowerCase().endsWith('.mod'))
      .map((item) => item.name)
      .sort(
        (a, b) =>
          Number(b.toLowerCase() === 'descriptor.mod') -
          Number(a.toLowerCase() === 'descriptor.mod')
      )
  } catch {
    return {}
  }

  for (const descriptor of descriptors) {
    try {
      const content = await fs.readFile(path.join(modPath, descriptor), 'utf8')
      const name = content.match(/^\s*name\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      const supportedVersion = content.match(/^\s*supported_version\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      const remoteFileId = content.match(/^\s*remote_file_id\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      // dependencies={ "Original Mod" } holds the untranslated name of the patched mod
      const block = content.match(/dependencies\s*=\s*\{([^}]*)\}/)?.[1] ?? ''
      const dependencies = [...block.matchAll(/"([^"]*)"/g)].map((match) => match[1].trim())

      if (name || supportedVersion) return { name, supportedVersion, remoteFileId, dependencies }
    } catch {
      // Unreadable descriptor is not worth failing the mod for
    }
  }

  return {}
}

/**
 * Read every localisation key a mod declares, grouped by language
 * @param modPath - The mod folder
 * @param translateKey - The game's folder translate key
 * @param errors - Collects unreadable folders
 * @returns Language to the keys it covers, and the source entries with their file
 */
const readModKeys = async (
  modPath: string,
  translateKey: string,
  errors: string[],
  notes?: { otherSpelling: boolean }
): Promise<ModKeys> => {
  const files = await listTradFiles(modPath, translateKey, false, errors, notes)
  const byLanguage = new Map<string, Map<string, LocalisationEntry>>()

  for (const file of files) {
    const described = parseLocalisationFile(file, translateKey)
    if (!described) continue

    let content: string
    try {
      content = await fs.readFile(file, 'utf8')
    } catch (error) {
      errors.push(`${file} : ${(error as Error).message}`)
      continue
    }

    // The l_<language> header is what the game actually reads, not the folder name
    const language =
      content.match(/^\s*l_([a-z_]+)\s*:/m)?.[1] ??
      described.rest.slice(0, -1).find((segment) => /^[a-z_]+$/.test(segment)) ??
      ''

    let keys = byLanguage.get(language)
    if (!keys) byLanguage.set(language, (keys = new Map()))

    for (const line of parseLocFile(content)) {
      if (!line.entry) continue
      const key = entryKey(line.entry.prefix)
      if (!keys.has(key)) keys.set(key, { key, file, described, language })
    }
  }

  return { files: files.length, byLanguage }
}

/**
 * Keys already translated for the mods, including the ones supplied by separate
 * localisation mods that declare a dependency on them
 * @param mods - Every discovered mod folder
 * @param translateKey - The game's folder translate key
 * @returns Mod id to language to the keys covered by its localisation mods
 */
const buildCoverage = async (
  mods: ModFolder[],
  translateKey: string,
  sourceLanguage: string
): Promise<Map<string, Coverage>> => {
  const descriptors = await mapWithConcurrency(mods, MOD_CONCURRENCY, (mod) =>
    readDescriptor(mod.path)
  )
  const allKeys = await mapWithConcurrency(mods, MOD_CONCURRENCY, (mod) =>
    readModKeys(mod.path, translateKey, [])
  )

  const byName = new Map<string, number>()
  mods.forEach((_mod, index) => {
    const name = descriptors[index].name
    if (name) byName.set(name, index)
  })

  const coverage = new Map<string, Coverage>()
  const credit = (targetIndex: number, patchIndex: number): void => {
    const target = mods[targetIndex]
    let entry = coverage.get(target.id)
    if (!entry) coverage.set(target.id, (entry = { byLanguage: new Map(), sources: [] }))

    const name = descriptors[patchIndex].name ?? mods[patchIndex].id
    if (!entry.sources.includes(name)) entry.sources.push(name)

    for (const [language, entries] of allKeys[patchIndex].byLanguage) {
      if (language === sourceLanguage) continue
      const merged = entry.byLanguage.get(language) ?? new Set<string>()
      for (const key of entries.keys()) merged.add(key)
      entry.byLanguage.set(language, merged)
    }
  }

  mods.forEach((_mod, index) => {
    for (const dependency of descriptors[index].dependencies ?? []) {
      const targetIndex = byName.get(dependency)
      if (targetIndex !== undefined && targetIndex !== index) credit(targetIndex, index)
    }
  })

  // Plenty of localisation mods never fill in dependencies. One that carries no source
  // language of its own but repeats another mod's keys is patching that mod, whatever its
  // descriptor says.
  mods.forEach((_mod, index) => {
    const keys = allKeys[index]
    const ownSource = keys.byLanguage.get(sourceLanguage)
    if (ownSource && ownSource.size > 0) return

    const translated = new Set<string>()
    for (const [language, entries] of keys.byLanguage) {
      if (language === sourceLanguage) continue
      for (const key of entries.keys()) translated.add(key)
    }
    if (translated.size === 0) return

    mods.forEach((_other, otherIndex) => {
      if (otherIndex === index) return
      const englishKeys = allKeys[otherIndex].byLanguage.get(sourceLanguage)
      if (!englishKeys || englishKeys.size === 0) return

      let shared = 0
      for (const key of translated) if (englishKeys.has(key)) shared++
      // Half of the patch landing on one mod is no coincidence
      if (shared > 0 && shared >= translated.size * KEY_OVERLAP_MATCH) credit(otherIndex, index)
    })
  })

  return coverage
}

/**
 * Turn any label into something usable as a folder name
 * @param value - The label
 * @param maxLength - Maximum length of the result, paths stay below the Windows limit
 * @returns The sanitized name, empty when nothing usable is left
 */
const sanitizeFolderName = (value: string, maxLength: number): string =>
  value
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase()
    .slice(0, maxLength)
    .replace(/_+$/g, '')

/**
 * Build the folder holding the files of one source mod inside the translation mod
 * @param mod - The source mod folder
 * @param name - The source mod declared name
 * @returns A folder name unique per source mod
 */
/**
 * Rename a target file so it can live next to an existing translation
 * @param target - The natural target path
 * @returns The same path with the partial marker before the extension
 */
const withPartialSuffix = (target: string): string => {
  const base = path.basename(target)
  // The games only load files whose name ends with _l_<language>.yml, so the marker
  // has to go before that tail, never after it
  const tail = base.match(/(_l_[a-z_]+\.yml)$/i)
  const renamed = tail
    ? `${base.slice(0, -tail[1].length)}${PARTIAL_SUFFIX}${tail[1]}`
    : `${base.slice(0, -path.extname(base).length)}${PARTIAL_SUFFIX}${path.extname(base)}`

  return path.join(path.dirname(target), renamed)
}

const getModNamespace = (mod: ModFolder, name: string): string => {
  const id = sanitizeFolderName(mod.id, 32)
  const label = sanitizeFolderName(name, 32)
  if (!id) return label || 'mod'
  // A workshop id carries no meaning, a folder already named after the mod needs no suffix
  return label && !id.includes(label) ? `${id}_${label}` : id
}

/**
 * Path of a target file inside the translation mod, relative to its localisation folder
 * The source language folder is dropped, everything else keeps the source mod layout
 * @param file - The described source file
 * @param targetPath - The already computed target path
 * @param sourceLanguage - The source language key
 * @returns The path segments below the target language folder
 */
const getTranslationModPath = (
  file: LocalisationFile,
  targetPath: string,
  sourceLanguage: string
): string[] => {
  const folders = file.rest.slice(0, -1)
  const languageIndex = folders.findIndex((segment) => segment.toLowerCase() === sourceLanguage)
  const kept =
    languageIndex === -1
      ? folders
      : [...folders.slice(0, languageIndex), ...folders.slice(languageIndex + 1)]

  return [...kept, path.basename(targetPath)]
}

/**
 * Reuse the game version the source mods declare rather than inventing one
 * @param results - The processed mods
 * @returns The most frequent supported_version, `*` when none was readable
 */
const pickSupportedVersion = (results: ModResult[]): string => {
  const counts = new Map<string, number>()
  // Mods that actually needed files describe the version this translation targets
  const relevant = results.filter((mod) => mod.createdCount > 0 && mod.supportedVersion)
  const source = relevant.length > 0 ? relevant : results.filter((mod) => mod.supportedVersion)

  for (const mod of source) {
    const version = mod.supportedVersion as string
    counts.set(version, (counts.get(version) ?? 0) + 1)
  }

  let best = '*'
  let bestCount = 0
  for (const [version, count] of counts) {
    if (count > bestCount) {
      best = version
      bestCount = count
    }
  }

  return best
}

/**
 * Content of a Paradox mod descriptor
 * @param mod - The translation mod description
 * @param withPath - Add the path field, required by the launcher on the outer .mod file
 * @returns The descriptor content
 */
const buildDescriptor = (mod: TranslationMod, withPath: boolean): string => {
  const lines = [
    'version="1.0"',
    'tags={',
    '\t"Translation"',
    '}',
    `name="${mod.name.replaceAll('"', "'")}"`,
    `supported_version="${mod.supportedVersion}"`
  ]
  if (withPath) lines.push(`path="mod/${mod.folder}"`)
  return `${lines.join('\n')}\n`
}

/**
 * Decide whether the selected folder is a single mod or a folder holding many mods
 * @param rootPath - The selected folder
 * @param translateKey - The game's folder translate key
 * @returns The mod folders to process, and whether the root itself is the mod
 */
const discoverMods = async (
  rootPath: string,
  translateKey: string
): Promise<{ mods: ModFolder[]; single: boolean }> => {
  const items = await fs.readdir(rootPath, { withFileTypes: true })

  const isSingleMod = items.some(
    (item) =>
      (item.isFile() && item.name.toLowerCase().endsWith('.mod')) ||
      (item.isDirectory() && item.name.toLowerCase() === translateKey)
  )

  if (isSingleMod) {
    return { mods: [{ id: path.basename(rootPath), path: rootPath }], single: true }
  }

  const subFolders = items
    .filter((item) => item.isDirectory() && !item.name.startsWith('.'))
    .map((item) => ({ id: item.name, path: path.join(rootPath, item.name) }))

  // Nothing below: treat the selection itself as the mod so the run still reports something
  if (subFolders.length === 0) {
    return { mods: [{ id: path.basename(rootPath), path: rootPath }], single: true }
  }

  return { mods: subFolders, single: false }
}

/** Set by the worker when the user asks to stop, checked between units of work */
export const cancellation = { requested: false, controller: new AbortController() }

/** What a mod needs, computed once and reused by the scan and the conversion */
interface ModPlan {
  name: string
  /** A localisation folder spelled the other way was found, so the game is likely wrong */
  otherSpelling?: boolean
  /** Total keys the source language declares */
  sourceKeys: number
  supportedVersion?: string
  localisationFiles: number
  sourceFiles: number
  /** Files to create, per target language */
  jobs: Record<string, CreationJob[]>
  errors: string[]
}

/**
 * Work out what is missing in a mod, without touching the disk
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param packed - Also compute the paths used inside a translation mod
 * @returns The plan for that mod
 */
const planMod = async (
  mod: ModFolder,
  request: Request,
  translateKey: string,
  packed: boolean,
  coverage?: Coverage
): Promise<ModPlan> => {
  const { sourceLanguage, targetLanguages } = request
  const errors: string[] = []
  const jobs: Record<string, CreationJob[]> = {}

  const descriptor = await readDescriptor(mod.path)
  const plan: ModPlan = {
    name: descriptor.name ?? mod.id,
    supportedVersion: descriptor.supportedVersion,
    localisationFiles: 0,
    sourceFiles: 0,
    sourceKeys: 0,
    jobs,
    errors
  }

  const notes = { otherSpelling: false }
  const modKeys = await readModKeys(mod.path, translateKey, errors, notes)
  plan.otherSpelling = notes.otherSpelling
  plan.localisationFiles = modKeys.files
  if (modKeys.files === 0) return plan

  const sourceEntries = modKeys.byLanguage.get(sourceLanguage)
  if (!sourceEntries || sourceEntries.size === 0) return plan
  plan.sourceFiles = new Set([...sourceEntries.values()].map((entry) => entry.file)).size
  plan.sourceKeys = sourceEntries.size

  const existingFiles = new Set<string>()
  for (const entries of modKeys.byLanguage.values()) {
    for (const entry of entries.values()) existingFiles.add(pathKey(entry.file))
  }

  for (const language of targetLanguages) {
    if (language === sourceLanguage) continue

    // A key counts as done when the mod itself translated it, or when a localisation
    // mod depending on this one did. Generating it again would shadow a real translation.
    const covered = new Set(modKeys.byLanguage.get(language)?.keys() ?? [])
    for (const key of coverage?.byLanguage.get(language) ?? []) covered.add(key)

    const byFile = new Map<string, { entry: LocalisationEntry; keys: Set<string> }>()
    for (const [key, entry] of sourceEntries) {
      if (covered.has(key)) continue
      let group = byFile.get(entry.file)
      if (!group) byFile.set(entry.file, (group = { entry, keys: new Set() }))
      group.keys.add(key)
    }

    const seen = new Set<string>()
    const languageJobs: CreationJob[] = []

    for (const { entry, keys } of byFile.values()) {
      let target = getTargetFile(entry.described, sourceLanguage, language)
      if (pathKey(target) === pathKey(entry.file)) continue
      // The natural name is taken by an existing translation: never rewrite it, sit beside it
      if (existingFiles.has(pathKey(target))) target = withPartialSuffix(target)
      const key = pathKey(target)
      if (seen.has(key)) continue
      seen.add(key)

      languageJobs.push({
        source: entry.file,
        target,
        packed: packed ? getTranslationModPath(entry.described, target, sourceLanguage) : [],
        keys
      })
    }

    if (languageJobs.length > 0) jobs[language] = languageJobs
  }

  return plan
}

/**
 * Count the lines a translator would have to handle
 * @param jobs - The planned files, per language
 * @returns The number of translatable lines
 */
const countTranslatableLines = async (jobs: Record<string, CreationJob[]>): Promise<number> => {
  const perFile = new Map<string, Map<string, boolean>>()
  let total = 0

  for (const language of Object.keys(jobs)) {
    for (const job of jobs[language]) {
      let translatable = perFile.get(job.source)
      if (!translatable) {
        translatable = new Map()
        try {
          const content = await fs.readFile(job.source, 'utf8')
          for (const line of parseLocFile(content)) {
            if (line.entry) {
              translatable.set(entryKey(line.entry.prefix), isTranslatable(line.entry.value))
            }
          }
        } catch {
          // An unreadable file simply contributes nothing to the estimate
        }
        perFile.set(job.source, translatable)
      }
      // Only the missing keys are sent to a translator, not the whole file
      for (const key of job.keys) if (translatable.get(key)) total++
    }
  }

  return total
}

/**
 * Report what a mod is missing, creating nothing
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param countLines - Read the source files to estimate the translation workload
 * @returns The scan result
 */
const scanMod = async (
  mod: ModFolder,
  request: Request,
  translateKey: string,
  countLines: boolean,
  coverage?: Coverage
): Promise<ScannedMod> => {
  const plan = await planMod(mod, request, translateKey, false, coverage)

  const missing: Record<string, number> = {}
  const missingKeys: Record<string, number> = {}
  let missingFiles = 0

  // Every requested language gets an entry, so "nothing missing" is stated rather than implied
  for (const language of request.targetLanguages) {
    if (language === request.sourceLanguage) continue
    missing[language] = 0
    missingKeys[language] = 0
  }

  for (const language of Object.keys(plan.jobs)) {
    missing[language] = plan.jobs[language].length
    missingKeys[language] = plan.jobs[language].reduce((sum, job) => sum + job.keys.size, 0)
    missingFiles += plan.jobs[language].length
  }

  return {
    id: mod.id,
    name: plan.name,
    path: mod.path,
    localisationFiles: plan.localisationFiles,
    sourceFiles: plan.sourceFiles,
    sourceKeys: plan.sourceKeys,
    otherSpelling: plan.otherSpelling,
    coveredBy: coverage?.sources ?? [],
    missing,
    missingKeys,
    missingFiles,
    missingLines: countLines && missingFiles > 0 ? await countTranslatableLines(plan.jobs) : 0,
    supportedVersion: plan.supportedVersion,
    errors: plan.errors
  }
}

/**
 * Build the content of one target file, translating its values when asked to
 * @param job - The file to create
 * @param sourceLanguage - The source language key
 * @param language - The target language key
 * @param translations - Known translations, missing entries stay in the source language
 * @returns The file content
 */
const buildTargetContent = async (
  job: CreationJob,
  sourceLanguage: string,
  language: string,
  translations?: Map<string, string>
): Promise<string> => {
  const sourceContent = await fs.readFile(job.source, 'utf8')
  const retagged = sourceContent.replaceAll(`l_${sourceLanguage}`, `l_${language}`)

  // Only the keys nobody translated yet, so the file never shadows an existing translation
  const kept = parseLocFile(retagged).filter((line, index) =>
    line.entry
      ? job.keys.has(entryKey(line.entry.prefix))
      : index === 0 || /^\s*l_[a-z_]+\s*:/.test(line.raw)
  )

  const lines = kept.map((line) => {
    const translated = line.entry && translations?.get(line.entry.value)
    return translated && line.entry
      ? { ...line, entry: { ...line.entry, value: translated } }
      : line
  })

  return `${serializeLocFile(lines)}\n`
}

/**
 * Create the missing translation files of a single mod
 * Every failure is captured in the result, one broken mod never stops the others
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param translationMod - Set when everything goes into one generated mod
 * @param engine - Set when the values must be translated, not just copied
 * @param languageNames - Game language key to its English name, used in the prompt
 * @returns The mod result
 */
const processMod = async (
  mod: ModFolder,
  request: Request,
  translateKey: string,
  translationMod?: TranslationMod,
  engine?: TranslationEngine,
  languageNames: Record<string, string> = {},
  coverage?: Coverage
): Promise<ModResult> => {
  const { sourceLanguage, mode, outputPath } = request
  const outputDir = mode === ConvertMode.EXTRACT_TO_FOLDER ? outputPath : undefined

  const created: Record<string, string[]> = {}
  const plan = await planMod(mod, request, translateKey, Boolean(translationMod), coverage)
  const result: ModResult = {
    id: mod.id,
    name: plan.name,
    path: mod.path,
    localisationFiles: plan.localisationFiles,
    sourceFiles: plan.sourceFiles,
    createdCount: 0,
    skippedCount: 0,
    failedCount: 0,
    created,
    truncated: 0,
    supportedVersion: plan.supportedVersion,
    errors: plan.errors
  }

  const namespace = translationMod ? getModNamespace(mod, plan.name) : ''

  for (const language of Object.keys(plan.jobs)) {
    if (cancellation.requested) break
    const jobs = plan.jobs[language]

    let translations: Map<string, string> | undefined
    if (engine) {
      const values: string[] = []
      for (const job of jobs) {
        try {
          const content = await fs.readFile(job.source, 'utf8')
          for (const line of parseLocFile(content)) {
            if (line.entry && isTranslatable(line.entry.value)) values.push(line.entry.value)
          }
        } catch {
          // The write below reports the unreadable file
        }
      }

      try {
        const outcome = await engine.translate(
          values,
          language,
          languageNames[language] ?? language
        )
        translations = outcome.results
        // Per mod numbers, so a run can be read back mod by mod rather than as one total
        result.translation = {
          translated: (result.translation?.translated ?? 0) + outcome.stats.translated,
          cached: (result.translation?.cached ?? 0) + outcome.stats.cached,
          failed: (result.translation?.failed ?? 0) + outcome.stats.failed
        }
      } catch (error) {
        // Backend down: fall back to copying, the run keeps its meaning
        plan.errors.push(`${language} : ${(error as Error).message}`)
        translations = new Map()
      }
    }

    if (cancellation.requested) break

    const languageFiles: string[] = []

    await Promise.all(
      jobs.map(async (job) => {
        try {
          const targetContent = await buildTargetContent(
            job,
            sourceLanguage,
            language,
            translations
          )

          let destination = job.target
          if (translationMod) {
            // Namespaced per source mod, two mods shipping the same file name never collide
            destination = path.join(
              translationMod.path,
              translateKey,
              language,
              namespace,
              ...job.packed
            )
          } else if (outputDir) {
            destination = path.join(outputDir, mod.id, path.relative(mod.path, job.target))
          }

          await fs.mkdir(path.dirname(destination), { recursive: true })
          // wx: never overwrite an existing translation, even outside the scanned folder
          await fs.writeFile(destination, targetContent, { encoding: 'utf8', flag: 'wx' })
          languageFiles.push(destination)
        } catch (error) {
          if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
            result.skippedCount++
          } else {
            result.failedCount++
            plan.errors.push(`${job.target} : ${(error as Error).message}`)
          }
        }
      })
    )

    if (languageFiles.length > 0) {
      result.createdCount += languageFiles.length
      created[language] = languageFiles.slice(0, MAX_LISTED_FILES_PER_MOD)
      result.truncated += languageFiles.length - created[language].length
    }
  }

  return result
}

/**
 * Game language key to its English name, the translator prompt needs a real language name
 * @param game - The game key
 * @returns braz_por to Portuguese, simp_chinese to Chinese, ...
 */
const getLanguageNames = (game: string): Record<string, string> => {
  const names: Record<string, string> = {}
  const languageKeys = GAMES[game].languageKeys as Record<string, string>
  for (const [code, key] of Object.entries(languageKeys)) {
    names[key] = LANGUAGES[code as keyof typeof LANGUAGES] ?? key
  }
  return names
}

/**
 * Report what every mod is missing, without writing anything
 * @param request - The scan request
 * @param workerPort - The worker port, used for progress
 * @returns The scan result
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const launchScan = async (request: Request, workerPort: any): Promise<ScanOutput> => {
  const translateKey = GAMES[request.game].translateKey
  const countLines = Boolean(request.translate?.enabled)

  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.SCANNING_FILES
  })

  const { mods } = await discoverMods(request.path, translateKey)
  const coverage = await buildCoverage(mods, translateKey, request.sourceLanguage)

  let done = 0
  const results = await mapWithConcurrency(mods, MOD_CONCURRENCY, async (mod) => {
    const result = await scanMod(mod, request, translateKey, countLines, coverage.get(mod.id))
    done++
    workerPort.postMessage({
      type: ConversionStatusType.PROGRESS,
      current: done,
      total: mods.length,
      modName: result.name
    })
    return result
  })

  const totals = results.reduce(
    (acc, mod) => ({
      mods: acc.mods + 1,
      missingFiles: acc.missingFiles + mod.missingFiles,
      missingLines: acc.missingLines + mod.missingLines,
      withoutLocalisation: acc.withoutLocalisation + (mod.localisationFiles === 0 ? 1 : 0),
      otherSpelling: acc.otherSpelling + (mod.otherSpelling ? 1 : 0)
    }),
    { mods: 0, missingFiles: 0, missingLines: 0, withoutLocalisation: 0, otherSpelling: 0 }
  )

  // Mods needing work first, the rest keeps the list readable
  const sorted = [...results].sort(
    (a, b) => b.missingFiles - a.missingFiles || a.name.localeCompare(b.name)
  )

  return { mods: sorted, totals }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const launchTranslation = async (request: Request, workerPort: any): Promise<ConversionOutput> => {
  const addLog = (message: string, values?: LogValues): void => {
    workerPort.postMessage({
      type: ConversionStatusType.LOG,
      ts: Date.now(),
      message,
      values
    })
  }

  const { path: rootPath, game, mode, modName, documentsPath, userDataPath, selectedMods } = request
  const translateKey = GAMES[game].translateKey

  let translationMod: TranslationMod | undefined
  let gameModsDir = ''
  if (mode === ConvertMode.CREATE_TRANSLATION_MOD) {
    if (!documentsPath) throw new Error('Documents folder could not be resolved')
    gameModsDir = path.join(documentsPath, 'Paradox Interactive', GAMES[game].userFolder, 'mod')

    const name = modName?.trim() || DEFAULT_MOD_NAME
    translationMod = {
      name,
      folder: sanitizeFolderName(name, 48) || DEFAULT_MOD_FOLDER,
      path: '',
      // Replaced once the source mods have been read
      supportedVersion: '*'
    }
    translationMod.path = path.join(gameModsDir, translationMod.folder)
  }

  addLog(ConversionLogMessage.STARTING)
  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.SCANNING_FILES
  })

  const discovered = await discoverMods(rootPath, translateKey)
  // Built from every discovered mod: a localisation mod the user did not tick still counts
  const coverage = await buildCoverage(discovered.mods, translateKey, request.sourceLanguage)
  // The user ticked the mods to handle in the scan list, an empty selection means everything
  const mods = selectedMods?.length
    ? discovered.mods.filter((mod) => selectedMods.includes(mod.id))
    : discovered.mods
  addLog(discovered.single ? ConversionLogMessage.SINGLE_MOD : ConversionLogMessage.MODS_FOUND, {
    count: mods.length
  })

  let engine: TranslationEngine | undefined
  let memory: TranslationMemory | undefined
  let lastProgress = { current: 0, total: mods.length, modName: '' }

  if (request.translate?.enabled) {
    if (!userDataPath) throw new Error('Translation memory folder could not be resolved')
    memory = new TranslationMemory(path.join(userDataPath, 'translation-memory'))
    // The renderer knows nothing about what the game is about, the worker does
    const config = { ...request.translate, domain: GAMES[game].domain }

    let glossary: Glossary | undefined
    if (config.gamePath) {
      // One target language at a time keeps the glossary small; the first is the one that
      // matters, the rest still gain from the domain sentence
      glossary = await loadGlossary(
        path.join(userDataPath, 'glossary'),
        config.gamePath,
        `${game}-${request.sourceLanguage}-${request.targetLanguages[0]}`,
        translateKey,
        request.sourceLanguage,
        request.targetLanguages[0]
      )
      addLog(ConversionLogMessage.GLOSSARY, {
        terms: glossary.terms.size,
        strings: glossary.exact.size
      })
    }

    engine = new TranslationEngine(
      config,
      memory,
      cancellation.controller.signal,
      (translation) => {
        workerPort.postMessage({
          type: ConversionStatusType.PROGRESS,
          ...lastProgress,
          translation
        })
      },
      glossary
    )
    addLog(ConversionLogMessage.TRANSLATING, {
      provider: request.translate.provider,
      model: request.translate.model
    })
  }

  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.PROCESSING_MODS
  })

  const languageNames = getLanguageNames(game)
  // A translation backend is the bottleneck, holding fewer mods in flight keeps memory low
  const concurrency = engine ? 2 : MOD_CONCURRENCY

  let done = 0
  const results = await mapWithConcurrency(mods, concurrency, async (mod) => {
    const result = await processMod(
      mod,
      request,
      translateKey,
      translationMod,
      engine,
      languageNames,
      coverage.get(mod.id)
    )
    done++
    lastProgress = { current: done, total: mods.length, modName: result.name }
    workerPort.postMessage({
      type: ConversionStatusType.PROGRESS,
      ...lastProgress,
      translation: engine?.getCounters()
    })
    return result
  })

  await memory?.flush()

  const totals = results.reduce(
    (acc, mod) => ({
      mods: acc.mods + 1,
      modsWithFiles: acc.modsWithFiles + (mod.createdCount > 0 ? 1 : 0),
      created: acc.created + mod.createdCount,
      skipped: acc.skipped + mod.skippedCount,
      failed: acc.failed + mod.failedCount,
      errors: acc.errors + mod.errors.length
    }),
    { mods: 0, modsWithFiles: 0, created: 0, skipped: 0, failed: 0, errors: 0 }
  )

  addLog(ConversionLogMessage.SUMMARY, {
    created: totals.created,
    mods: totals.modsWithFiles,
    failed: totals.failed
  })

  if (translationMod && totals.created > 0) {
    translationMod.supportedVersion = pickSupportedVersion(results)
    await fs.mkdir(translationMod.path, { recursive: true })
    // Both files are needed: the launcher reads mod/<folder>.mod, the game reads the inner one
    await fs.writeFile(
      path.join(gameModsDir, `${translationMod.folder}.mod`),
      buildDescriptor(translationMod, true),
      'utf8'
    )
    await fs.writeFile(
      path.join(translationMod.path, 'descriptor.mod'),
      buildDescriptor(translationMod, false),
      'utf8'
    )
    addLog(ConversionLogMessage.MOD_CREATED, { name: translationMod.name })
  }

  addLog(ConversionLogMessage.DONE)

  // Mods that produced something first, then the ones that need attention
  const sortedMods = [...results].sort(
    (a, b) =>
      b.createdCount - a.createdCount ||
      b.errors.length - a.errors.length ||
      a.name.localeCompare(b.name)
  )

  return {
    mods: sortedMods,
    translationMod,
    translation: engine?.getCounters(),
    cancelled: cancellation.requested,
    totals
  }
}

/**
 * Entry point of the worker: scan the mods or actually create the files
 * @param request - What to do
 * @param workerPort - The worker port, used for logs and progress
 * @returns The scan or conversion result
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const run = async (request: Request, workerPort: any): Promise<ScanOutput | ConversionOutput> =>
  request.action === WorkerAction.SCAN
    ? launchScan(request, workerPort)
    : launchTranslation(request, workerPort)

export default run
