import * as fs from 'fs/promises'
import type { Dirent } from 'fs'
import * as path from 'path'
import { GAMES, LANGUAGES } from '../../global/constants'
import {
  ConversionLogMessage,
  ConversionOutput,
  ConversionStatus,
  ConversionStatusType,
  ConvertMode,
  KeyReport,
  KeyState,
  LogValues,
  ModResult,
  ScannedMod,
  ScanOutput,
  TranslateConfig,
  TranslationMod,
  WorkerAction
} from '../../global/types'
import { writeRunReport } from '../report'
import { TranslationEngine } from '../translate/engine'
import { Glossary, loadGlossary } from '../translate/glossary'
import { TranslationMemory } from '../translate/memory'
import { entryKey, isTranslatable, parseLocFile, serializeLocFile } from '../translate/yml'

export interface Request {
  action?: WorkerAction
  path: string
  game: string
  sourceLanguage: string
  targetLanguages: string[]
  mode: ConvertMode
  outputPath?: string
  /** Name of the mod generated by ConvertMode.CREATE_TRANSLATION_MOD */
  modName?: string
  /** Documents folder, resolved by the main process since Electron is not available here */
  documentsPath?: string
  /** Folder holding the translation memory, also resolved by the main process */
  userDataPath?: string
  /** Mod folder names to process, every discovered mod when left out */
  selectedMods?: string[]
  translate?: TranslateConfig
}

/** How many mods are scanned at the same time */
const MOD_CONCURRENCY = 8

/** Share of a localisation mod key set that must land on one mod to call it a patch of it */
const KEY_OVERLAP_MATCH = 0.5

/** How many created files are reported per mod, the rest is only counted */
const MAX_LISTED_FILES_PER_MOD = 100

/**
 * Suffix for a generated file that sits next to an existing translation.
 * Topping up an existing file would mean rewriting someone else's work, so the missing
 * keys go into a file of their own instead.
 */
const PARTIAL_SUFFIX = '_ptt_missing'

/** Fallbacks when the user leaves the translation mod name empty */
const DEFAULT_MOD_NAME = 'Missing Translations'
const DEFAULT_MOD_FOLDER = 'missing_translations'

/** A .yml file located inside a localisation folder */
interface LocalisationFile {
  path: string
  /** Index of the localisation segment in the splitted path */
  locIndex: number
  /** Path segments after the localisation folder, last one being the file name */
  rest: string[]
}

interface ModFolder {
  id: string
  path: string
}

interface CreationJob {
  source: string
  target: string
  /** Path below the language folder, used when packing into a translation mod */
  packed: string[]
  /**
   * Every key the target file must hold, mapped to its source value. Keys somebody else
   * already translated are not in here: writing them would shadow their work.
   */
  keys: Map<string, string>
  /**
   * Of those keys, the ones an earlier run of ours already translated, mapped to that
   * translation. The generated file is rewritten whole on every run, so they have to be
   * carried over, and none of them is ever sent to a translator twice.
   */
  known: Map<string, string>
}

interface Descriptor {
  name?: string
  supportedVersion?: string
  remoteFileId?: string
  dependencies?: string[]
}

interface LocalisationEntry {
  key: string
  file: string
  described: LocalisationFile
  language: string
  /** The quoted value, needed to tell a real translation from a copied source string */
  value: string
}

interface Coverage {
  byLanguage: Map<string, Set<string>>
  /** Names of the mods providing the coverage, shown so the user can see who covers what */
  sources: string[]
}

interface ModKeys {
  files: number
  /** Language to key to where that key was declared */
  byLanguage: Map<string, Map<string, LocalisationEntry>>
}

/** Split a path on both separators so the logic is not Windows only */
const splitPath = (value: string): string[] => value.split(/[\\/]+/)

/** Comparable form of a path: same separator, same case */
const pathKey = (value: string): string => value.replace(/[\\/]+/g, '/').toLowerCase()

/**
 * Run an async task over a list, a few items at a time
 * @param items - The items to process
 * @param limit - Maximum number of tasks running at once
 * @param task - The task to run
 * @returns The results, in the order of `items`
 */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  task: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length)
  let cursor = 0

  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) {
      const index = cursor++
      if (index >= items.length) return
      results[index] = await task(items[index], index)
    }
  })

  await Promise.all(runners)
  return results
}

/**
 * Recursively list all .yml translation files of a mod
 * A file counts only if one of its parent folders is the game's localisation folder
 * @param dirPath - The directory path to search
 * @param translateKey - The game's folder translate key
 * @param inLocalisation - True once we are below the localisation folder
 * @param errors - Collects unreadable folders instead of throwing
 * @returns Array of .yml file paths
 */
async function listTradFiles(
  dirPath: string,
  translateKey: string,
  inLocalisation: boolean,
  errors: string[],
  notes?: { otherSpelling: boolean }
): Promise<string[]> {
  let items: Dirent[]
  try {
    items = await fs.readdir(dirPath, { withFileTypes: true })
  } catch (error) {
    errors.push(`${dirPath} : ${(error as Error).message}`)
    return []
  }

  const ymlFiles: string[] = []
  const subDirectories: Promise<string[]>[] = []

  for (const item of items) {
    const fullPath = path.join(dirPath, item.name)
    const name = item.name.toLowerCase()

    if (item.isDirectory()) {
      // The two spellings are a classic mix-up: CK3 says localization, the others localisation
      if (notes && name !== translateKey && (name === 'localisation' || name === 'localization')) {
        notes.otherSpelling = true
      }
      // replace/ used to be skipped; real mods keep translated strings there, so it counts
      subDirectories.push(
        listTradFiles(
          fullPath,
          translateKey,
          inLocalisation || name === translateKey,
          errors,
          notes
        )
      )
    } else if (inLocalisation && item.isFile() && name.endsWith('.yml')) {
      ymlFiles.push(fullPath)
    }
  }

  const nested = await Promise.all(subDirectories)
  return ymlFiles.concat(...nested)
}

/**
 * Describe a localisation file relative to its localisation folder
 * @param filePath - The file path
 * @param translateKey - The game's folder translate key
 * @returns The described file, or null if it is not below a localisation folder
 */
const parseLocalisationFile = (filePath: string, translateKey: string): LocalisationFile | null => {
  const segments = splitPath(filePath)
  // Deepest localisation folder wins, a mod can nest one inside another folder
  const locIndex = segments.map((segment) => segment.toLowerCase()).lastIndexOf(translateKey)
  if (locIndex === -1 || locIndex === segments.length - 1) return null
  return { path: filePath, locIndex, rest: segments.slice(locIndex + 1) }
}

/**
 * Build the path a file would have in the target language
 * Only the segments below the localisation folder are rewritten, so a mod folder
 * named after a language (english_names_fix, ...) is never mangled
 * @param file - The described source file
 * @param sourceLanguage - The source language key
 * @param targetLanguage - The target language key
 * @returns The target file path
 */
const getTargetFile = (
  file: LocalisationFile,
  sourceLanguage: string,
  targetLanguage: string
): string => {
  const segments = splitPath(file.path)
  const head = segments.slice(0, file.locIndex + 1)
  const lastIndex = file.rest.length - 1

  const tail = file.rest.map((segment, index) => {
    // The file name carries the language tag (foo_l_english.yml), rewrite every occurrence
    if (index === lastIndex) return segment.replaceAll(sourceLanguage, targetLanguage)
    // A folder is renamed only when it *is* the language, never on a partial match
    return segment.toLowerCase() === sourceLanguage ? targetLanguage : segment
  })

  return [...head, ...tail].join(path.sep)
}

/**
 * Read what we need from a mod descriptor
 * @param modPath - The mod folder
 * @returns The declared name and supported version, both optional
 */
const readDescriptor = async (modPath: string): Promise<Descriptor> => {
  let descriptors: string[]
  try {
    const items = await fs.readdir(modPath, { withFileTypes: true })
    descriptors = items
      .filter((item) => item.isFile() && item.name.toLowerCase().endsWith('.mod'))
      .map((item) => item.name)
      .sort(
        (a, b) =>
          Number(b.toLowerCase() === 'descriptor.mod') -
          Number(a.toLowerCase() === 'descriptor.mod')
      )
  } catch {
    return {}
  }

  for (const descriptor of descriptors) {
    try {
      const content = await fs.readFile(path.join(modPath, descriptor), 'utf8')
      const name = content.match(/^\s*name\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      const supportedVersion = content.match(/^\s*supported_version\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      const remoteFileId = content.match(/^\s*remote_file_id\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      // dependencies={ "Original Mod" } holds the untranslated name of the patched mod
      const block = content.match(/dependencies\s*=\s*\{([^}]*)\}/)?.[1] ?? ''
      const dependencies = [...block.matchAll(/"([^"]*)"/g)].map((match) => match[1].trim())

      if (name || supportedVersion) return { name, supportedVersion, remoteFileId, dependencies }
    } catch {
      // Unreadable descriptor is not worth failing the mod for
    }
  }

  return {}
}

/**
 * Read every localisation key a mod declares, grouped by language
 * @param modPath - The mod folder
 * @param translateKey - The game's folder translate key
 * @param errors - Collects unreadable folders
 * @returns Language to the keys it covers, and the source entries with their file
 */
const readModKeys = async (
  modPath: string,
  translateKey: string,
  errors: string[],
  notes?: { otherSpelling: boolean }
): Promise<ModKeys> => {
  const files = await listTradFiles(modPath, translateKey, false, errors, notes)
  const byLanguage = new Map<string, Map<string, LocalisationEntry>>()

  for (const file of files) {
    const described = parseLocalisationFile(file, translateKey)
    if (!described) continue

    let content: string
    try {
      content = await fs.readFile(file, 'utf8')
    } catch (error) {
      errors.push(`${file} : ${(error as Error).message}`)
      continue
    }

    // The l_<language> header is what the game actually reads, not the folder name
    const language =
      content.match(/^\s*l_([a-z_]+)\s*:/m)?.[1] ??
      described.rest.slice(0, -1).find((segment) => /^[a-z_]+$/.test(segment)) ??
      ''

    let keys = byLanguage.get(language)
    if (!keys) byLanguage.set(language, (keys = new Map()))

    for (const line of parseLocFile(content)) {
      if (!line.entry) continue
      const key = entryKey(line.entry.prefix)
      if (!keys.has(key)) {
        keys.set(key, { key, file, described, language, value: line.entry.value })
      }
    }
  }

  return { files: files.length, byLanguage }
}

/**
 * Keys already translated for the mods, including the ones supplied by separate
 * localisation mods that declare a dependency on them
 * @param mods - Every discovered mod folder
 * @param translateKey - The game's folder translate key
 * @returns Mod id to language to the keys covered by its localisation mods
 */
const buildCoverage = async (
  mods: ModFolder[],
  translateKey: string,
  sourceLanguage: string
): Promise<Map<string, Coverage>> => {
  const descriptors = await mapWithConcurrency(mods, MOD_CONCURRENCY, (mod) =>
    readDescriptor(mod.path)
  )
  const allKeys = await mapWithConcurrency(mods, MOD_CONCURRENCY, (mod) =>
    readModKeys(mod.path, translateKey, [])
  )

  const byName = new Map<string, number>()
  mods.forEach((_mod, index) => {
    const name = descriptors[index].name
    if (name) byName.set(name, index)
  })

  const coverage = new Map<string, Coverage>()
  const credit = (targetIndex: number, patchIndex: number): void => {
    const target = mods[targetIndex]
    let entry = coverage.get(target.id)
    if (!entry) coverage.set(target.id, (entry = { byLanguage: new Map(), sources: [] }))

    const name = descriptors[patchIndex].name ?? mods[patchIndex].id
    if (!entry.sources.includes(name)) entry.sources.push(name)

    for (const [language, entries] of allKeys[patchIndex].byLanguage) {
      if (language === sourceLanguage) continue
      const merged = entry.byLanguage.get(language) ?? new Set<string>()
      for (const key of entries.keys()) merged.add(key)
      entry.byLanguage.set(language, merged)
    }
  }

  mods.forEach((_mod, index) => {
    for (const dependency of descriptors[index].dependencies ?? []) {
      const targetIndex = byName.get(dependency)
      if (targetIndex !== undefined && targetIndex !== index) credit(targetIndex, index)
    }
  })

  // Plenty of localisation mods never fill in dependencies. One that carries no source
  // language of its own but repeats another mod's keys is patching that mod, whatever its
  // descriptor says.
  mods.forEach((_mod, index) => {
    const keys = allKeys[index]
    const ownSource = keys.byLanguage.get(sourceLanguage)
    if (ownSource && ownSource.size > 0) return

    const translated = new Set<string>()
    for (const [language, entries] of keys.byLanguage) {
      if (language === sourceLanguage) continue
      for (const key of entries.keys()) translated.add(key)
    }
    if (translated.size === 0) return

    mods.forEach((_other, otherIndex) => {
      if (otherIndex === index) return
      const englishKeys = allKeys[otherIndex].byLanguage.get(sourceLanguage)
      if (!englishKeys || englishKeys.size === 0) return

      let shared = 0
      for (const key of translated) if (englishKeys.has(key)) shared++
      // Half of the patch landing on one mod is no coincidence
      if (shared > 0 && shared >= translated.size * KEY_OVERLAP_MATCH) credit(otherIndex, index)
    })
  })

  return coverage
}

/** One key our own generated mod already holds */
interface GeneratedEntry {
  value: string
  file: string
}

/** What a previous run of this tool left in the game mod folder */
interface GeneratedMod {
  path: string
  /** Namespace folder to language to key, the namespace naming the source mod */
  byNamespace: Map<string, Map<string, Map<string, GeneratedEntry>>>
}

/**
 * Read back the mod this tool generated on an earlier run.
 *
 * Without it a second scan reports everything as missing again, because the generated mod
 * lives under Documents and never appears in the scanned workshop folder. Its first level
 * folder below the language is the namespace built by `getModNamespace`, which is what ties
 * a generated file back to the mod it was generated for.
 * @param modPath - The generated mod folder
 * @param translateKey - The game's folder translate key
 * @returns The generated keys, or undefined when nothing was generated yet
 */
const readGeneratedMod = async (
  modPath: string,
  translateKey: string
): Promise<GeneratedMod | undefined> => {
  try {
    await fs.access(modPath)
  } catch {
    return undefined
  }

  const keys = await readModKeys(modPath, translateKey, [])
  const byNamespace = new Map<string, Map<string, Map<string, GeneratedEntry>>>()

  for (const [language, entries] of keys.byLanguage) {
    for (const entry of entries.values()) {
      // rest is [language, namespace, ...path, file]; a file sitting straight under the
      // language folder was not written by us and belongs to no mod
      const namespace = entry.described.rest.length > 2 ? entry.described.rest[1] : ''
      let languages = byNamespace.get(namespace)
      if (!languages) byNamespace.set(namespace, (languages = new Map()))
      let map = languages.get(language)
      if (!map) languages.set(language, (map = new Map()))
      map.set(entry.key, { value: entry.value, file: entry.file })
    }
  }

  return { path: modPath, byNamespace }
}

/**
 * Where the generated mod of a request lives, whether or not it exists yet
 * @param request - The scan or conversion request
 * @returns The mod folder and the game mod directory holding it
 */
const resolveGeneratedMod = (
  request: Request
): { modsDir: string; folder: string; path: string } | undefined => {
  if (!request.documentsPath) return undefined
  const modsDir = path.join(
    request.documentsPath,
    'Paradox Interactive',
    GAMES[request.game].userFolder,
    'mod'
  )
  const name = request.modName?.trim() || DEFAULT_MOD_NAME
  const folder = sanitizeFolderName(name, 48) || DEFAULT_MOD_FOLDER
  return { modsDir, folder, path: path.join(modsDir, folder) }
}

/**
 * Take our own output out of the list of mods to scan.
 *
 * A copy of the generated mod sitting in the scanned folder, which is what happens when it
 * is moved next to the workshop mods, carries no source language and repeats other mods'
 * keys, so the coverage heuristics read it as a third party localisation mod. It would then
 * vouch for its own English leftovers and hide the very work it was generated to do.
 * @param mods - Every discovered mod folder
 * @param generatedFolder - Folder name of the generated mod
 * @returns The mods to scan, and the path of the copy that was dropped
 */
const dropOurOwnMod = (
  mods: ModFolder[],
  generatedFolder?: string
): { mods: ModFolder[]; selfCopy?: string } => {
  if (!generatedFolder) return { mods }
  const ours = mods.find((mod) => mod.id.toLowerCase() === generatedFolder.toLowerCase())
  return ours ? { mods: mods.filter((mod) => mod !== ours), selfCopy: ours.path } : { mods }
}

/**
 * Whether a generated value is a real translation or the source string copied verbatim
 * @param generated - The value found in the generated mod
 * @param source - The value in the source language
 * @returns True when the translator produced nothing for this key
 */
const isUntranslated = (generated: string, source: string): boolean =>
  generated.trim() === source.trim()

/**
 * Turn any label into something usable as a folder name
 * @param value - The label
 * @param maxLength - Maximum length of the result, paths stay below the Windows limit
 * @returns The sanitized name, empty when nothing usable is left
 */
const sanitizeFolderName = (value: string, maxLength: number): string =>
  value
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase()
    .slice(0, maxLength)
    .replace(/_+$/g, '')

/**
 * Build the folder holding the files of one source mod inside the translation mod
 * @param mod - The source mod folder
 * @param name - The source mod declared name
 * @returns A folder name unique per source mod
 */
/**
 * Rename a target file so it can live next to an existing translation
 * @param target - The natural target path
 * @returns The same path with the partial marker before the extension
 */
const withPartialSuffix = (target: string): string => {
  const base = path.basename(target)
  // The games only load files whose name ends with _l_<language>.yml, so the marker
  // has to go before that tail, never after it
  const tail = base.match(/(_l_[a-z_]+\.yml)$/i)
  const renamed = tail
    ? `${base.slice(0, -tail[1].length)}${PARTIAL_SUFFIX}${tail[1]}`
    : `${base.slice(0, -path.extname(base).length)}${PARTIAL_SUFFIX}${path.extname(base)}`

  return path.join(path.dirname(target), renamed)
}

const getModNamespace = (mod: ModFolder, name: string): string => {
  const id = sanitizeFolderName(mod.id, 32)
  const label = sanitizeFolderName(name, 32)
  if (!id) return label || 'mod'
  // A workshop id carries no meaning, a folder already named after the mod needs no suffix
  return label && !id.includes(label) ? `${id}_${label}` : id
}

/**
 * Path of a target file inside the translation mod, relative to its localisation folder
 * The source language folder is dropped, everything else keeps the source mod layout
 * @param file - The described source file
 * @param targetPath - The already computed target path
 * @param sourceLanguage - The source language key
 * @returns The path segments below the target language folder
 */
const getTranslationModPath = (
  file: LocalisationFile,
  targetPath: string,
  sourceLanguage: string
): string[] => {
  const folders = file.rest.slice(0, -1)
  const languageIndex = folders.findIndex((segment) => segment.toLowerCase() === sourceLanguage)
  const kept =
    languageIndex === -1
      ? folders
      : [...folders.slice(0, languageIndex), ...folders.slice(languageIndex + 1)]

  return [...kept, path.basename(targetPath)]
}

/**
 * Reuse the game version the source mods declare rather than inventing one
 * @param results - The processed mods
 * @returns The most frequent supported_version, `*` when none was readable
 */
const pickSupportedVersion = (results: ModResult[]): string => {
  const counts = new Map<string, number>()
  // Mods that actually needed files describe the version this translation targets
  const relevant = results.filter((mod) => mod.createdCount > 0 && mod.supportedVersion)
  const source = relevant.length > 0 ? relevant : results.filter((mod) => mod.supportedVersion)

  for (const mod of source) {
    const version = mod.supportedVersion as string
    counts.set(version, (counts.get(version) ?? 0) + 1)
  }

  let best = '*'
  let bestCount = 0
  for (const [version, count] of counts) {
    if (count > bestCount) {
      best = version
      bestCount = count
    }
  }

  return best
}

/**
 * Content of a Paradox mod descriptor
 * @param mod - The translation mod description
 * @param withPath - Add the path field, required by the launcher on the outer .mod file
 * @returns The descriptor content
 */
const buildDescriptor = (mod: TranslationMod, withPath: boolean): string => {
  const lines = [
    'version="1.0"',
    'tags={',
    '\t"Translation"',
    '}',
    `name="${mod.name.replaceAll('"', "'")}"`,
    `supported_version="${mod.supportedVersion}"`
  ]
  if (withPath) lines.push(`path="mod/${mod.folder}"`)
  return `${lines.join('\n')}\n`
}

/**
 * Decide whether the selected folder is a single mod or a folder holding many mods
 * @param rootPath - The selected folder
 * @param translateKey - The game's folder translate key
 * @returns The mod folders to process, and whether the root itself is the mod
 */
const discoverMods = async (
  rootPath: string,
  translateKey: string
): Promise<{ mods: ModFolder[]; single: boolean }> => {
  const items = await fs.readdir(rootPath, { withFileTypes: true })

  const isSingleMod = items.some(
    (item) =>
      (item.isFile() && item.name.toLowerCase().endsWith('.mod')) ||
      (item.isDirectory() && item.name.toLowerCase() === translateKey)
  )

  if (isSingleMod) {
    return { mods: [{ id: path.basename(rootPath), path: rootPath }], single: true }
  }

  const subFolders = items
    .filter((item) => item.isDirectory() && !item.name.startsWith('.'))
    .map((item) => ({ id: item.name, path: path.join(rootPath, item.name) }))

  // Nothing below: treat the selection itself as the mod so the run still reports something
  if (subFolders.length === 0) {
    return { mods: [{ id: path.basename(rootPath), path: rootPath }], single: true }
  }

  return { mods: subFolders, single: false }
}

/** Set by the worker when the user asks to stop, checked between units of work */
export const cancellation = { requested: false, controller: new AbortController() }

/** What a mod needs, computed once and reused by the scan and the conversion */
interface ModPlan {
  name: string
  /** Folder this mod owns inside the generated translation mod */
  namespace: string
  /** A localisation folder spelled the other way was found, so the game is likely wrong */
  otherSpelling?: boolean
  /** Total keys the source language declares */
  sourceKeys: number
  supportedVersion?: string
  localisationFiles: number
  sourceFiles: number
  /** Files to create, per target language */
  jobs: Record<string, CreationJob[]>
  /** Keys already translated by anyone, per target language */
  covered: Record<string, number>
  /** Keys our own generated mod holds in the source language, per target language */
  english: Record<string, number>
  /** Keys the backend answered with the source text itself, per target language */
  kept: Record<string, number>
  /** Keys our own generated mod holds although somebody else translates them */
  shadowed: Record<string, number>
  /** Key by key state, only filled when the caller asked for the detail */
  keyStates: KeyReport[]
  errors: string[]
}

interface PlanOptions {
  translateKey: string
  /** Also compute the paths used inside a translation mod */
  packed: boolean
  coverage?: Coverage
  /** What an earlier run already wrote, so its output is not generated a second time */
  generated?: GeneratedMod
  /**
   * The translation memory, already loaded for the target languages. It is the only way to
   * tell a string the backend refused from one it answered with the source text.
   */
  memory?: TranslationMemory
  /** Collect the state of every key, which costs memory on a large collection */
  detail?: boolean
}

/**
 * Work out what is missing in a mod, without touching the disk
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param options - How to plan, see PlanOptions
 * @returns The plan for that mod
 */
const planMod = async (
  mod: ModFolder,
  request: Request,
  options: PlanOptions
): Promise<ModPlan> => {
  const { sourceLanguage, targetLanguages } = request
  const { translateKey, packed, coverage, generated, memory, detail } = options
  const errors: string[] = []
  const jobs: Record<string, CreationJob[]> = {}

  const descriptor = await readDescriptor(mod.path)
  const name = descriptor.name ?? mod.id
  const plan: ModPlan = {
    name,
    namespace: getModNamespace(mod, name),
    supportedVersion: descriptor.supportedVersion,
    localisationFiles: 0,
    sourceFiles: 0,
    sourceKeys: 0,
    jobs,
    covered: {},
    english: {},
    kept: {},
    shadowed: {},
    keyStates: [],
    errors
  }

  const notes = { otherSpelling: false }
  const modKeys = await readModKeys(mod.path, translateKey, errors, notes)
  plan.otherSpelling = notes.otherSpelling
  plan.localisationFiles = modKeys.files
  if (modKeys.files === 0) return plan

  const sourceEntries = modKeys.byLanguage.get(sourceLanguage)
  if (!sourceEntries || sourceEntries.size === 0) return plan
  plan.sourceFiles = new Set([...sourceEntries.values()].map((entry) => entry.file)).size
  plan.sourceKeys = sourceEntries.size

  const existingFiles = new Set<string>()
  for (const entries of modKeys.byLanguage.values()) {
    for (const entry of entries.values()) existingFiles.add(pathKey(entry.file))
  }

  const generatedForMod = generated?.byNamespace.get(plan.namespace)

  for (const language of targetLanguages) {
    if (language === sourceLanguage) continue

    // A key counts as done when the mod itself translated it, or when a localisation
    // mod depending on this one did. Generating it again would shadow a real translation.
    const own = modKeys.byLanguage.get(language)
    const patched = coverage?.byLanguage.get(language)
    const ours = generatedForMod?.get(language)

    let covered = 0
    let english = 0
    let kept = 0
    let shadowed = 0

    const byFile = new Map<
      string,
      { entry: LocalisationEntry; keys: Map<string, string>; known: Map<string, string> }
    >()
    const record = (
      entry: LocalisationEntry,
      state: KeyState,
      provider?: string,
      shadowedByUs?: boolean
    ): void => {
      if (!detail) return
      plan.keyStates.push({
        modId: mod.id,
        modName: plan.name,
        language,
        key: entry.key,
        file: entry.file,
        source: entry.value,
        state,
        provider,
        markupOnly: !isTranslatable(entry.value),
        shadowed: shadowedByUs
      })
    }

    for (const [key, entry] of sourceEntries) {
      // Somebody else's translation: our file must not hold this key at all. When it does,
      // our mod loads last and hides their work until the next run drops the key.
      if (own?.has(key) || patched?.has(key)) {
        covered++
        const hidden = ours?.has(key) ?? false
        if (hidden) shadowed++
        record(
          entry,
          own?.has(key) ? KeyState.OWN : KeyState.PATCH,
          own?.has(key) ? plan.name : coverage?.sources.join(', '),
          hidden
        )
        continue
      }

      let group = byFile.get(entry.file)
      if (!group) byFile.set(entry.file, (group = { entry, keys: new Map(), known: new Map() }))
      group.keys.set(key, entry.value)

      const mine = ours?.get(key)
      if (!mine) {
        record(entry, KeyState.MISSING)
        continue
      }

      // A value we copied verbatim is not a translation. Markup and numbers are copied on
      // purpose and never sent anywhere, so only real text left as-is is in question.
      const verbatim = isUntranslated(mine.value, entry.value) && isTranslatable(entry.value)
      // The memory settles it: an entry holding the source text means the backend answered
      // and answered with that. A proper name it chose to keep is worth no retry, only the
      // same bill. No entry at all means nothing ever came back for this string.
      if (verbatim && memory?.get(language, entry.value) !== entry.value) {
        english++
        record(entry, KeyState.ENGLISH, mine.file)
        continue
      }

      covered++
      group.known.set(key, mine.value)
      if (verbatim) {
        kept++
        record(entry, KeyState.KEPT, mine.file)
      } else {
        record(entry, KeyState.GENERATED, mine.file)
      }
    }

    plan.covered[language] = covered
    plan.english[language] = english
    plan.kept[language] = kept
    plan.shadowed[language] = shadowed

    const seen = new Set<string>()
    const languageJobs: CreationJob[] = []

    for (const { entry, keys, known } of byFile.values()) {
      let target = getTargetFile(entry.described, sourceLanguage, language)
      if (pathKey(target) === pathKey(entry.file)) continue
      // The natural name is taken by an existing translation: never rewrite it, sit beside it
      if (existingFiles.has(pathKey(target))) target = withPartialSuffix(target)
      const key = pathKey(target)
      if (seen.has(key)) continue
      seen.add(key)

      languageJobs.push({
        source: entry.file,
        target,
        packed: packed ? getTranslationModPath(entry.described, target, sourceLanguage) : [],
        keys,
        known
      })
    }

    if (languageJobs.length > 0) jobs[language] = languageJobs
  }

  return plan
}

/**
 * Count the lines a translator would have to handle
 * @param jobs - The planned files, per language
 * @returns The number of translatable lines
 */
const countTranslatableLines = (jobs: Record<string, CreationJob[]>): number => {
  let total = 0
  for (const language of Object.keys(jobs)) {
    for (const job of jobs[language]) {
      // Only what still needs a translator: the rest is copied or carried over for free
      for (const value of pendingValues(job)) if (isTranslatable(value)) total++
    }
  }
  return total
}

/** Source values of the keys nothing has translated yet */
const pendingValues = (job: CreationJob): string[] =>
  [...job.keys].filter(([key]) => !job.known.has(key)).map(([, value]) => value)

/** Keys of a job that still need work, the rest is only carried over */
const pendingCount = (job: CreationJob): number => job.keys.size - job.known.size

/**
 * Report what a mod is missing, creating nothing
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param countLines - Read the source files to estimate the translation workload
 * @returns The scan result
 */
const scanMod = async (
  mod: ModFolder,
  request: Request,
  options: PlanOptions,
  countLines: boolean
): Promise<{ scanned: ScannedMod; keyStates: KeyReport[] }> => {
  const plan = await planMod(mod, request, options)

  const missing: Record<string, number> = {}
  const missingKeys: Record<string, number> = {}
  const coveredKeys: Record<string, number> = {}
  const englishKeys: Record<string, number> = {}
  const keptKeys: Record<string, number> = {}
  const shadowedKeys: Record<string, number> = {}
  let missingFiles = 0

  // Every requested language gets an entry, so "nothing missing" is stated rather than implied
  for (const language of request.targetLanguages) {
    if (language === request.sourceLanguage) continue
    missing[language] = 0
    missingKeys[language] = 0
    coveredKeys[language] = plan.covered[language] ?? 0
    englishKeys[language] = plan.english[language] ?? 0
    keptKeys[language] = plan.kept[language] ?? 0
    shadowedKeys[language] = plan.shadowed[language] ?? 0
  }

  for (const language of Object.keys(plan.jobs)) {
    // A file whose keys are all carried over from an earlier run is no work: it is
    // rewritten unchanged and must not be reported as missing
    const pending = plan.jobs[language].filter((job) => pendingCount(job) > 0)
    missing[language] = pending.length
    missingKeys[language] = pending.reduce((sum, job) => sum + pendingCount(job), 0)
    missingFiles += pending.length
  }

  return {
    keyStates: plan.keyStates,
    scanned: {
      id: mod.id,
      name: plan.name,
      path: mod.path,
      localisationFiles: plan.localisationFiles,
      sourceFiles: plan.sourceFiles,
      sourceKeys: plan.sourceKeys,
      otherSpelling: plan.otherSpelling,
      coveredBy: options.coverage?.sources ?? [],
      missing,
      missingKeys,
      coveredKeys,
      englishKeys,
      keptKeys,
      shadowedKeys,
      missingFiles,
      missingLines: countLines && missingFiles > 0 ? countTranslatableLines(plan.jobs) : 0,
      supportedVersion: plan.supportedVersion,
      errors: plan.errors
    }
  }
}

/**
 * Build the content of one target file, translating its values when asked to
 * @param job - The file to create
 * @param sourceLanguage - The source language key
 * @param language - The target language key
 * @param translations - Known translations, missing entries stay in the source language
 * @returns The file content
 */
const buildTargetContent = async (
  job: CreationJob,
  sourceLanguage: string,
  language: string,
  translations?: Map<string, string>
): Promise<string> => {
  const sourceContent = await fs.readFile(job.source, 'utf8')
  const retagged = sourceContent.replaceAll(`l_${sourceLanguage}`, `l_${language}`)

  // Only the keys nobody translated yet, so the file never shadows an existing translation
  const kept = parseLocFile(retagged).filter((line, index) =>
    line.entry
      ? job.keys.has(entryKey(line.entry.prefix))
      : index === 0 || /^\s*l_[a-z_]+\s*:/.test(line.raw)
  )

  const lines = kept.map((line) => {
    if (!line.entry) return line
    // What we translated on an earlier run wins: it is already in the file being rewritten
    const translated =
      job.known.get(entryKey(line.entry.prefix)) ?? translations?.get(line.entry.value)
    return translated ? { ...line, entry: { ...line.entry, value: translated } } : line
  })

  return `${serializeLocFile(lines)}\n`
}

/**
 * Create the missing translation files of a single mod
 * Every failure is captured in the result, one broken mod never stops the others
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param translationMod - Set when everything goes into one generated mod
 * @param engine - Set when the values must be translated, not just copied
 * @param languageNames - Game language key to its English name, used in the prompt
 * @returns The mod result
 */
const processMod = async (
  mod: ModFolder,
  request: Request,
  options: PlanOptions,
  translationMod?: TranslationMod,
  engine?: TranslationEngine,
  languageNames: Record<string, string> = {}
): Promise<{ result: ModResult; untranslated: KeyReport[] }> => {
  const { sourceLanguage, mode, outputPath } = request
  const { translateKey } = options
  const outputDir = mode === ConvertMode.EXTRACT_TO_FOLDER ? outputPath : undefined

  const created: Record<string, string[]> = {}
  const plan = await planMod(mod, request, options)
  const result: ModResult = {
    id: mod.id,
    name: plan.name,
    path: mod.path,
    localisationFiles: plan.localisationFiles,
    sourceFiles: plan.sourceFiles,
    createdCount: 0,
    skippedCount: 0,
    failedCount: 0,
    prunedCount: 0,
    created,
    truncated: 0,
    supportedVersion: plan.supportedVersion,
    errors: plan.errors
  }

  const namespace = plan.namespace
  const untranslated: KeyReport[] = []
  /** Files this run put into the generated mod, per language, so the rest can be pruned */
  const producedByLanguage = new Map<string, Set<string>>()

  for (const language of Object.keys(plan.jobs)) {
    if (cancellation.requested) break
    const jobs = plan.jobs[language]

    let translations: Map<string, string> | undefined
    if (engine) {
      // Only what is still untranslated: sending the whole source file would pay again for
      // strings another mod, or an earlier run of ours, already covered
      const values: string[] = []
      for (const job of jobs) {
        for (const value of pendingValues(job)) if (isTranslatable(value)) values.push(value)
      }

      try {
        const outcome = await engine.translate(
          values,
          language,
          languageNames[language] ?? language
        )
        translations = outcome.results
        // Per mod numbers, so a run can be read back mod by mod rather than as one total
        result.translation = {
          translated: (result.translation?.translated ?? 0) + outcome.stats.translated,
          cached: (result.translation?.cached ?? 0) + outcome.stats.cached,
          failed: (result.translation?.failed ?? 0) + outcome.stats.failed
        }
      } catch (error) {
        // Backend down: fall back to copying, the run keeps its meaning
        plan.errors.push(`${language} : ${(error as Error).message}`)
        translations = new Map()
      }
    }

    if (cancellation.requested) break

    // What is written now and still holds English is what the next run has to retry
    if (engine) {
      for (const job of jobs) {
        for (const [key, value] of job.keys) {
          if (job.known.has(key) || !isTranslatable(value) || translations?.has(value)) continue
          const refusal = engine.refusalFor(value)
          untranslated.push({
            modId: mod.id,
            modName: plan.name,
            language,
            key,
            file: job.source,
            source: value,
            state: KeyState.ENGLISH,
            reason: refusal
              ? `${refusal.reason}${refusal.detail ? `: ${refusal.detail}` : ''}`
              : 'not attempted'
          })
        }
      }
    }

    const languageFiles: string[] = []
    const produced = new Set<string>()
    producedByLanguage.set(language, produced)

    await Promise.all(
      jobs.map(async (job) => {
        try {
          const targetContent = await buildTargetContent(
            job,
            sourceLanguage,
            language,
            translations
          )

          let destination = job.target
          if (translationMod) {
            // Namespaced per source mod, two mods shipping the same file name never collide
            destination = path.join(
              translationMod.path,
              translateKey,
              language,
              namespace,
              ...job.packed
            )
          } else if (outputDir) {
            destination = path.join(outputDir, mod.id, path.relative(mod.path, job.target))
          }

          await fs.mkdir(path.dirname(destination), { recursive: true })

          if (translationMod) {
            // Our own generated mod is ours to rewrite: a previous run may have left English
            // in it, and refusing to overwrite would make that first bad pass permanent.
            // Rewriting a file that did not change would only churn the disk, though.
            produced.add(pathKey(destination))
            const before = await fs.readFile(destination, 'utf8').catch(() => undefined)
            if (before === targetContent) {
              result.skippedCount++
              return
            }
            await fs.writeFile(destination, targetContent, 'utf8')
          } else {
            // wx: never overwrite an existing translation, even outside the scanned folder
            await fs.writeFile(destination, targetContent, { encoding: 'utf8', flag: 'wx' })
          }

          languageFiles.push(destination)
        } catch (error) {
          if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
            result.skippedCount++
          } else {
            result.failedCount++
            plan.errors.push(`${job.target} : ${(error as Error).message}`)
          }
        }
      })
    )

    if (languageFiles.length > 0) {
      result.createdCount += languageFiles.length
      created[language] = languageFiles.slice(0, MAX_LISTED_FILES_PER_MOD)
      result.truncated += languageFiles.length - created[language].length
    }
  }

  // Never prune on a mod we failed to read: an unreadable folder plans no job, and taking
  // that for "nothing is missing any more" would delete a good translation
  if (
    translationMod &&
    !cancellation.requested &&
    plan.sourceKeys > 0 &&
    plan.errors.length === 0
  ) {
    result.prunedCount = await pruneNamespace(
      translationMod,
      translateKey,
      namespace,
      request.targetLanguages.filter((language) => language !== sourceLanguage),
      producedByLanguage,
      plan.errors
    )
  }

  return { result, untranslated }
}

/**
 * Drop generated files this run no longer needs.
 *
 * A key covered since the last run, by the mod itself or by a localisation mod, leaves a
 * file behind that would keep shadowing the real translation. Only the folder this mod owns
 * inside the generated mod is touched, and only for the languages the run handled.
 * @param translationMod - The generated mod
 * @param translateKey - The game's folder translate key
 * @param namespace - The folder belonging to this source mod
 * @param languages - The target languages this run handled
 * @param produced - Files written by this run, per language
 * @param errors - Collects deletion failures
 * @returns How many files were removed
 */
const pruneNamespace = async (
  translationMod: TranslationMod,
  translateKey: string,
  namespace: string,
  languages: string[],
  produced: Map<string, Set<string>>,
  errors: string[]
): Promise<number> => {
  let removed = 0

  for (const language of languages) {
    const folder = path.join(translationMod.path, translateKey, language, namespace)
    const kept = produced.get(language) ?? new Set<string>()
    const existing = await listTradFiles(folder, translateKey, true, [])

    for (const file of existing) {
      if (kept.has(pathKey(file))) continue
      try {
        await fs.rm(file)
        removed++
      } catch (error) {
        errors.push(`${file} : ${(error as Error).message}`)
      }
    }
  }

  return removed
}

/**
 * Game language key to its English name, the translator prompt needs a real language name
 * @param game - The game key
 * @returns braz_por to Portuguese, simp_chinese to Chinese, ...
 */
const getLanguageNames = (game: string): Record<string, string> => {
  const names: Record<string, string> = {}
  const languageKeys = GAMES[game].languageKeys as Record<string, string>
  for (const [code, key] of Object.entries(languageKeys)) {
    names[key] = LANGUAGES[code as keyof typeof LANGUAGES] ?? key
  }
  return names
}

/** Sum a per language record, the UI and the CLI both want one number */
const sumLanguages = (counts: Record<string, number>): number =>
  Object.values(counts).reduce((sum, count) => sum + count, 0)

/**
 * The translation memory of a request, loaded for every target language.
 *
 * A scan writes nothing and would not need it, except to answer one question no file on disk
 * can: whether a string left in the source language was refused or answered that way.
 * @param request - The scan or conversion request
 * @returns The loaded memory, or undefined when there is nowhere to read it from
 */
const loadMemory = async (
  userDataPath: string,
  languages: string[]
): Promise<TranslationMemory> => {
  const memory = new TranslationMemory(path.join(userDataPath, 'translation-memory'))
  await Promise.all(languages.map((language) => memory.load(language)))
  return memory
}

/** The same, for a caller that may have no data folder to read from */
const loadMemoryFor = async (request: Request): Promise<TranslationMemory | undefined> =>
  request.userDataPath ? loadMemory(request.userDataPath, request.targetLanguages) : undefined

/**
 * Report what every mod is missing, without writing anything
 * @param request - The scan request
 * @param workerPort - The worker port, used for progress
 * @param detail - Also return the state of every key, used by the CLI audit
 * @returns The scan result, and the key states when they were asked for
 */
const launchScan = async (
  request: Request,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  workerPort: any,
  detail = false
): Promise<ScanOutput & { keyStates?: KeyReport[] }> => {
  const translateKey = GAMES[request.game].translateKey
  const countLines = Boolean(request.translate?.enabled)

  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.SCANNING_FILES
  })

  // Our own output normally lives under Documents, so without reading it back a second
  // scan reports everything as missing again
  const target = resolveGeneratedMod(request)
  const generated = target ? await readGeneratedMod(target.path, translateKey) : undefined
  const memory = await loadMemoryFor(request)

  const discovered = await discoverMods(request.path, translateKey)
  const { mods, selfCopy } = dropOurOwnMod(discovered.mods, target?.folder)
  const coverage = await buildCoverage(mods, translateKey, request.sourceLanguage)

  let done = 0
  const results = await mapWithConcurrency(mods, MOD_CONCURRENCY, async (mod) => {
    const result = await scanMod(
      mod,
      request,
      { translateKey, packed: false, coverage: coverage.get(mod.id), generated, memory, detail },
      countLines
    )
    done++
    workerPort.postMessage({
      type: ConversionStatusType.PROGRESS,
      current: done,
      total: mods.length,
      modName: result.scanned.name
    })
    return result
  })

  const scanned = results.map((result) => result.scanned)
  const totals = scanned.reduce(
    (acc, mod) => ({
      mods: acc.mods + 1,
      missingFiles: acc.missingFiles + mod.missingFiles,
      missingLines: acc.missingLines + mod.missingLines,
      withoutLocalisation: acc.withoutLocalisation + (mod.localisationFiles === 0 ? 1 : 0),
      otherSpelling: acc.otherSpelling + (mod.otherSpelling ? 1 : 0),
      coveredKeys: acc.coveredKeys + sumLanguages(mod.coveredKeys),
      englishKeys: acc.englishKeys + sumLanguages(mod.englishKeys),
      keptKeys: acc.keptKeys + sumLanguages(mod.keptKeys),
      shadowedKeys: acc.shadowedKeys + sumLanguages(mod.shadowedKeys)
    }),
    {
      mods: 0,
      missingFiles: 0,
      missingLines: 0,
      withoutLocalisation: 0,
      otherSpelling: 0,
      coveredKeys: 0,
      englishKeys: 0,
      keptKeys: 0,
      shadowedKeys: 0
    }
  )

  // Mods needing work first, the rest keeps the list readable
  const sorted = [...scanned].sort(
    (a, b) => b.missingFiles - a.missingFiles || a.name.localeCompare(b.name)
  )

  return {
    mods: sorted,
    totals,
    selfCopy,
    generatedMod: generated && summariseGeneratedMod(generated, scanned),
    keyStates: detail ? results.flatMap((result) => result.keyStates) : undefined
  }
}

/**
 * What the generated mod contributes, and what in it belongs to nothing any more
 * @param generated - The generated mod read back from disk
 * @param scanned - The scanned mods
 * @returns The summary shown next to the scan totals
 */
const summariseGeneratedMod = (
  generated: GeneratedMod,
  scanned: ScannedMod[]
): NonNullable<ScanOutput['generatedMod']> => {
  const english = scanned.reduce((sum, mod) => sum + sumLanguages(mod.englishKeys), 0)
  const kept = scanned.reduce((sum, mod) => sum + sumLanguages(mod.keptKeys), 0)
  const shadowed = scanned.reduce((sum, mod) => sum + sumLanguages(mod.shadowedKeys), 0)

  // A namespace matching no scanned mod comes from a mod that was renamed or unsubscribed
  const known = new Set<string>()
  for (const mod of scanned) known.add(getModNamespace({ id: mod.id, path: mod.path }, mod.name))

  let total = 0
  const orphanNamespaces: string[] = []
  for (const [namespace, languages] of generated.byNamespace) {
    if (namespace !== '' && !known.has(namespace)) {
      orphanNamespaces.push(namespace)
      continue
    }
    for (const keys of languages.values()) total += keys.size
  }

  return {
    path: generated.path,
    translated: total - english - kept - shadowed,
    english,
    kept,
    shadowed,
    orphanNamespaces
  }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const launchTranslation = async (request: Request, workerPort: any): Promise<ConversionOutput> => {
  const addLog = (message: string, values?: LogValues): void => {
    workerPort.postMessage({
      type: ConversionStatusType.LOG,
      ts: Date.now(),
      message,
      values
    })
  }

  const { path: rootPath, game, mode, modName, userDataPath, selectedMods } = request
  const translateKey = GAMES[game].translateKey

  let translationMod: TranslationMod | undefined
  let gameModsDir = ''
  const target = resolveGeneratedMod(request)
  if (mode === ConvertMode.CREATE_TRANSLATION_MOD) {
    if (!target) throw new Error('Documents folder could not be resolved')
    gameModsDir = target.modsDir
    translationMod = {
      name: modName?.trim() || DEFAULT_MOD_NAME,
      folder: target.folder,
      path: target.path,
      // Replaced once the source mods have been read
      supportedVersion: '*'
    }
  }

  const startedAt = Date.now()
  addLog(ConversionLogMessage.STARTING)
  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.SCANNING_FILES
  })

  const discovered = await discoverMods(rootPath, translateKey)
  // A copy of our own mod among the scanned ones would vouch for its own English leftovers
  const { mods: sources, selfCopy } = dropOurOwnMod(discovered.mods, target?.folder)
  if (selfCopy) addLog(ConversionLogMessage.SELF_COPY, { path: selfCopy })
  // Built from every discovered mod: a localisation mod the user did not tick still counts
  const coverage = await buildCoverage(sources, translateKey, request.sourceLanguage)
  // What an earlier run already translated is not paid for twice; what it left in English is
  const generated = translationMod
    ? await readGeneratedMod(translationMod.path, translateKey)
    : undefined
  // The user ticked the mods to handle in the scan list, an empty selection means everything
  const mods = selectedMods?.length
    ? sources.filter((mod) => selectedMods.includes(mod.id))
    : sources
  addLog(discovered.single ? ConversionLogMessage.SINGLE_MOD : ConversionLogMessage.MODS_FOUND, {
    count: mods.length
  })

  let engine: TranslationEngine | undefined
  let memory: TranslationMemory | undefined
  let lastProgress = { current: 0, total: mods.length, modName: '' }

  if (request.translate?.enabled) {
    if (!userDataPath) throw new Error('Translation memory folder could not be resolved')
    // Loaded up front rather than lazily by the engine: planning happens first and needs it
    // to tell a refused string from one the backend answered with the source text
    memory = await loadMemory(userDataPath, request.targetLanguages)
    // The renderer knows nothing about what the game is about, the worker does
    const config = { ...request.translate, domain: GAMES[game].domain }

    let glossary: Glossary | undefined
    if (config.gamePath) {
      // One target language at a time keeps the glossary small; the first is the one that
      // matters, the rest still gain from the domain sentence
      glossary = await loadGlossary(
        path.join(userDataPath, 'glossary'),
        config.gamePath,
        `${game}-${request.sourceLanguage}-${request.targetLanguages[0]}`,
        translateKey,
        request.sourceLanguage,
        request.targetLanguages[0]
      )
      addLog(ConversionLogMessage.GLOSSARY, {
        terms: glossary.terms.size,
        strings: glossary.exact.size
      })
    }

    engine = new TranslationEngine(
      config,
      memory,
      cancellation.controller.signal,
      (translation) => {
        workerPort.postMessage({
          type: ConversionStatusType.PROGRESS,
          ...lastProgress,
          translation
        })
      },
      glossary
    )
    addLog(ConversionLogMessage.TRANSLATING, {
      provider: request.translate.provider,
      model: request.translate.model
    })
  }

  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.PROCESSING_MODS
  })

  const languageNames = getLanguageNames(game)
  // A translation backend is the bottleneck, holding fewer mods in flight keeps memory low
  const concurrency = engine ? 2 : MOD_CONCURRENCY

  let done = 0
  const outcomes = await mapWithConcurrency(mods, concurrency, async (mod) => {
    const outcome = await processMod(
      mod,
      request,
      {
        translateKey,
        packed: Boolean(translationMod),
        coverage: coverage.get(mod.id),
        generated,
        memory
      },
      translationMod,
      engine,
      languageNames
    )
    done++
    lastProgress = { current: done, total: mods.length, modName: outcome.result.name }
    workerPort.postMessage({
      type: ConversionStatusType.PROGRESS,
      ...lastProgress,
      translation: engine?.getCounters()
    })
    return outcome
  })

  await memory?.flush()

  const results = outcomes.map((outcome) => outcome.result)
  const totals = results.reduce(
    (acc, mod) => ({
      mods: acc.mods + 1,
      modsWithFiles: acc.modsWithFiles + (mod.createdCount > 0 ? 1 : 0),
      created: acc.created + mod.createdCount,
      skipped: acc.skipped + mod.skippedCount,
      failed: acc.failed + mod.failedCount,
      pruned: acc.pruned + mod.prunedCount,
      errors: acc.errors + mod.errors.length
    }),
    { mods: 0, modsWithFiles: 0, created: 0, skipped: 0, failed: 0, pruned: 0, errors: 0 }
  )

  addLog(ConversionLogMessage.SUMMARY, {
    created: totals.created,
    mods: totals.modsWithFiles,
    failed: totals.failed
  })

  if (translationMod && totals.created > 0) {
    translationMod.supportedVersion = pickSupportedVersion(results)
    await fs.mkdir(translationMod.path, { recursive: true })
    // Both files are needed: the launcher reads mod/<folder>.mod, the game reads the inner one
    await fs.writeFile(
      path.join(gameModsDir, `${translationMod.folder}.mod`),
      buildDescriptor(translationMod, true),
      'utf8'
    )
    await fs.writeFile(
      path.join(translationMod.path, 'descriptor.mod'),
      buildDescriptor(translationMod, false),
      'utf8'
    )
    addLog(ConversionLogMessage.MOD_CREATED, { name: translationMod.name })
  }

  // A count of failures says nothing about what to fix, the key by key list does
  const reportPath = userDataPath
    ? await writeRunReport(path.join(userDataPath, 'reports'), {
        startedAt,
        finishedAt: Date.now(),
        request,
        totals,
        counters: engine?.getCounters(),
        refusals: engine?.getRefusals(),
        mods: results,
        untranslated: outcomes.flatMap((outcome) => outcome.untranslated),
        translationMod
      })
    : undefined

  addLog(ConversionLogMessage.DONE)

  // Mods that produced something first, then the ones that need attention
  const sortedMods = [...results].sort(
    (a, b) =>
      b.createdCount - a.createdCount ||
      b.errors.length - a.errors.length ||
      a.name.localeCompare(b.name)
  )

  return {
    mods: sortedMods,
    reportPath,
    translationMod,
    translation: engine?.getCounters(),
    cancelled: cancellation.requested,
    totals
  }
}

/**
 * Entry point of the worker: scan the mods or actually create the files
 * @param request - What to do
 * @param workerPort - The worker port, used for logs and progress
 * @returns The scan or conversion result
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const run = async (request: Request, workerPort: any): Promise<ScanOutput | ConversionOutput> =>
  request.action === WorkerAction.SCAN
    ? launchScan(request, workerPort)
    : launchTranslation(request, workerPort)

// Both are driven straight by the CLI, which needs the key level detail a worker message
// could not carry and has no worker to speak through
export { launchScan, launchTranslation }

export default run
