import * as fs from 'fs/promises'
import type { Dirent } from 'fs'
import * as path from 'path'
import { GAMES, LANGUAGES } from '../../global/constants'
import {
  ConversionLogMessage,
  ConversionOutput,
  ConversionStatus,
  ConversionStatusType,
  ConvertMode,
  LogValues,
  ModResult,
  ScannedMod,
  ScanOutput,
  TranslateConfig,
  TranslationMod,
  WorkerAction
} from '../../global/types'
import { TranslationEngine } from '../translate/engine'
import { TranslationMemory } from '../translate/memory'
import { isTranslatable, parseLocFile, serializeLocFile } from '../translate/yml'

export interface Request {
  action?: WorkerAction
  path: string
  game: string
  sourceLanguage: string
  targetLanguages: string[]
  mode: ConvertMode
  outputPath?: string
  /** Name of the mod generated by ConvertMode.CREATE_TRANSLATION_MOD */
  modName?: string
  /** Documents folder, resolved by the main process since Electron is not available here */
  documentsPath?: string
  /** Folder holding the translation memory, also resolved by the main process */
  userDataPath?: string
  /** Mod folder names to process, every discovered mod when left out */
  selectedMods?: string[]
  translate?: TranslateConfig
}

/** How many mods are scanned at the same time */
const MOD_CONCURRENCY = 8

/** How many created files are reported per mod, the rest is only counted */
const MAX_LISTED_FILES_PER_MOD = 100

/** Localisation subfolder holding overrides of vanilla files, out of scope for now */
const EXCLUDED_LOC_FOLDER = 'replace'

/** Fallbacks when the user leaves the translation mod name empty */
const DEFAULT_MOD_NAME = 'Missing Translations'
const DEFAULT_MOD_FOLDER = 'missing_translations'

/** A .yml file located inside a localisation folder */
interface LocalisationFile {
  path: string
  /** Index of the localisation segment in the splitted path */
  locIndex: number
  /** Path segments after the localisation folder, last one being the file name */
  rest: string[]
}

interface ModFolder {
  id: string
  path: string
}

interface CreationJob {
  source: string
  target: string
  /** Path below the language folder, used when packing into a translation mod */
  packed: string[]
}

/** Split a path on both separators so the logic is not Windows only */
const splitPath = (value: string): string[] => value.split(/[\\/]+/)

/** Comparable form of a path: same separator, same case */
const pathKey = (value: string): string => value.replace(/[\\/]+/g, '/').toLowerCase()

/**
 * Run an async task over a list, a few items at a time
 * @param items - The items to process
 * @param limit - Maximum number of tasks running at once
 * @param task - The task to run
 * @returns The results, in the order of `items`
 */
async function mapWithConcurrency<T, R>(
  items: T[],
  limit: number,
  task: (item: T, index: number) => Promise<R>
): Promise<R[]> {
  const results: R[] = new Array(items.length)
  let cursor = 0

  const runners = Array.from({ length: Math.min(limit, items.length) }, async () => {
    for (;;) {
      const index = cursor++
      if (index >= items.length) return
      results[index] = await task(items[index], index)
    }
  })

  await Promise.all(runners)
  return results
}

/**
 * Recursively list all .yml translation files of a mod
 * A file counts only if one of its parent folders is the game's localisation folder
 * @param dirPath - The directory path to search
 * @param translateKey - The game's folder translate key
 * @param inLocalisation - True once we are below the localisation folder
 * @param errors - Collects unreadable folders instead of throwing
 * @returns Array of .yml file paths
 */
async function listTradFiles(
  dirPath: string,
  translateKey: string,
  inLocalisation: boolean,
  errors: string[]
): Promise<string[]> {
  let items: Dirent[]
  try {
    items = await fs.readdir(dirPath, { withFileTypes: true })
  } catch (error) {
    errors.push(`${dirPath} : ${(error as Error).message}`)
    return []
  }

  const ymlFiles: string[] = []
  const subDirectories: Promise<string[]>[] = []

  for (const item of items) {
    const fullPath = path.join(dirPath, item.name)
    const name = item.name.toLowerCase()

    if (item.isDirectory()) {
      // TODO: Manage the replace folder
      if (inLocalisation && name === EXCLUDED_LOC_FOLDER) continue
      subDirectories.push(
        listTradFiles(fullPath, translateKey, inLocalisation || name === translateKey, errors)
      )
    } else if (inLocalisation && item.isFile() && name.endsWith('.yml')) {
      ymlFiles.push(fullPath)
    }
  }

  const nested = await Promise.all(subDirectories)
  return ymlFiles.concat(...nested)
}

/**
 * Describe a localisation file relative to its localisation folder
 * @param filePath - The file path
 * @param translateKey - The game's folder translate key
 * @returns The described file, or null if it is not below a localisation folder
 */
const parseLocalisationFile = (filePath: string, translateKey: string): LocalisationFile | null => {
  const segments = splitPath(filePath)
  // Deepest localisation folder wins, a mod can nest one inside another folder
  const locIndex = segments.map((segment) => segment.toLowerCase()).lastIndexOf(translateKey)
  if (locIndex === -1 || locIndex === segments.length - 1) return null
  return { path: filePath, locIndex, rest: segments.slice(locIndex + 1) }
}

/**
 * Tell if a localisation file belongs to the source language
 * Either it sits in a folder named after the language, or its name carries the language tag
 * @param file - The described localisation file
 * @param sourceLanguage - The source language key
 * @returns True if the file is a source language file
 */
const isSourceLanguageFile = (file: LocalisationFile, sourceLanguage: string): boolean => {
  const fileName = file.rest[file.rest.length - 1].toLowerCase()
  const folders = file.rest.slice(0, -1).map((segment) => segment.toLowerCase())

  return (
    folders.includes(sourceLanguage) ||
    fileName.includes(`l_${sourceLanguage}`) ||
    (folders.length === 0 && fileName.includes(sourceLanguage))
  )
}

/**
 * Build the path a file would have in the target language
 * Only the segments below the localisation folder are rewritten, so a mod folder
 * named after a language (english_names_fix, ...) is never mangled
 * @param file - The described source file
 * @param sourceLanguage - The source language key
 * @param targetLanguage - The target language key
 * @returns The target file path
 */
const getTargetFile = (
  file: LocalisationFile,
  sourceLanguage: string,
  targetLanguage: string
): string => {
  const segments = splitPath(file.path)
  const head = segments.slice(0, file.locIndex + 1)
  const lastIndex = file.rest.length - 1

  const tail = file.rest.map((segment, index) => {
    // The file name carries the language tag (foo_l_english.yml), rewrite every occurrence
    if (index === lastIndex) return segment.replaceAll(sourceLanguage, targetLanguage)
    // A folder is renamed only when it *is* the language, never on a partial match
    return segment.toLowerCase() === sourceLanguage ? targetLanguage : segment
  })

  return [...head, ...tail].join(path.sep)
}

/**
 * Read what we need from a mod descriptor
 * @param modPath - The mod folder
 * @returns The declared name and supported version, both optional
 */
const readDescriptor = async (
  modPath: string
): Promise<{ name?: string; supportedVersion?: string }> => {
  let descriptors: string[]
  try {
    const items = await fs.readdir(modPath, { withFileTypes: true })
    descriptors = items
      .filter((item) => item.isFile() && item.name.toLowerCase().endsWith('.mod'))
      .map((item) => item.name)
      .sort(
        (a, b) =>
          Number(b.toLowerCase() === 'descriptor.mod') -
          Number(a.toLowerCase() === 'descriptor.mod')
      )
  } catch {
    return {}
  }

  for (const descriptor of descriptors) {
    try {
      const content = await fs.readFile(path.join(modPath, descriptor), 'utf8')
      const name = content.match(/^\s*name\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      const supportedVersion = content.match(/^\s*supported_version\s*=\s*"([^"]*)"/m)?.[1]?.trim()
      if (name || supportedVersion) return { name, supportedVersion }
    } catch {
      // Unreadable descriptor is not worth failing the mod for
    }
  }

  return {}
}

/**
 * Turn any label into something usable as a folder name
 * @param value - The label
 * @param maxLength - Maximum length of the result, paths stay below the Windows limit
 * @returns The sanitized name, empty when nothing usable is left
 */
const sanitizeFolderName = (value: string, maxLength: number): string =>
  value
    .replace(/[^a-zA-Z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .toLowerCase()
    .slice(0, maxLength)
    .replace(/_+$/g, '')

/**
 * Build the folder holding the files of one source mod inside the translation mod
 * @param mod - The source mod folder
 * @param name - The source mod declared name
 * @returns A folder name unique per source mod
 */
const getModNamespace = (mod: ModFolder, name: string): string => {
  const id = sanitizeFolderName(mod.id, 32)
  const label = sanitizeFolderName(name, 32)
  if (!id) return label || 'mod'
  // A workshop id carries no meaning, a folder already named after the mod needs no suffix
  return label && !id.includes(label) ? `${id}_${label}` : id
}

/**
 * Path of a target file inside the translation mod, relative to its localisation folder
 * The source language folder is dropped, everything else keeps the source mod layout
 * @param file - The described source file
 * @param targetPath - The already computed target path
 * @param sourceLanguage - The source language key
 * @returns The path segments below the target language folder
 */
const getTranslationModPath = (
  file: LocalisationFile,
  targetPath: string,
  sourceLanguage: string
): string[] => {
  const folders = file.rest.slice(0, -1)
  const languageIndex = folders.findIndex((segment) => segment.toLowerCase() === sourceLanguage)
  const kept =
    languageIndex === -1
      ? folders
      : [...folders.slice(0, languageIndex), ...folders.slice(languageIndex + 1)]

  return [...kept, path.basename(targetPath)]
}

/**
 * Reuse the game version the source mods declare rather than inventing one
 * @param results - The processed mods
 * @returns The most frequent supported_version, `*` when none was readable
 */
const pickSupportedVersion = (results: ModResult[]): string => {
  const counts = new Map<string, number>()
  // Mods that actually needed files describe the version this translation targets
  const relevant = results.filter((mod) => mod.createdCount > 0 && mod.supportedVersion)
  const source = relevant.length > 0 ? relevant : results.filter((mod) => mod.supportedVersion)

  for (const mod of source) {
    const version = mod.supportedVersion as string
    counts.set(version, (counts.get(version) ?? 0) + 1)
  }

  let best = '*'
  let bestCount = 0
  for (const [version, count] of counts) {
    if (count > bestCount) {
      best = version
      bestCount = count
    }
  }

  return best
}

/**
 * Content of a Paradox mod descriptor
 * @param mod - The translation mod description
 * @param withPath - Add the path field, required by the launcher on the outer .mod file
 * @returns The descriptor content
 */
const buildDescriptor = (mod: TranslationMod, withPath: boolean): string => {
  const lines = [
    'version="1.0"',
    'tags={',
    '\t"Translation"',
    '}',
    `name="${mod.name.replaceAll('"', "'")}"`,
    `supported_version="${mod.supportedVersion}"`
  ]
  if (withPath) lines.push(`path="mod/${mod.folder}"`)
  return `${lines.join('\n')}\n`
}

/**
 * Decide whether the selected folder is a single mod or a folder holding many mods
 * @param rootPath - The selected folder
 * @param translateKey - The game's folder translate key
 * @returns The mod folders to process, and whether the root itself is the mod
 */
const discoverMods = async (
  rootPath: string,
  translateKey: string
): Promise<{ mods: ModFolder[]; single: boolean }> => {
  const items = await fs.readdir(rootPath, { withFileTypes: true })

  const isSingleMod = items.some(
    (item) =>
      (item.isFile() && item.name.toLowerCase().endsWith('.mod')) ||
      (item.isDirectory() && item.name.toLowerCase() === translateKey)
  )

  if (isSingleMod) {
    return { mods: [{ id: path.basename(rootPath), path: rootPath }], single: true }
  }

  const subFolders = items
    .filter((item) => item.isDirectory() && !item.name.startsWith('.'))
    .map((item) => ({ id: item.name, path: path.join(rootPath, item.name) }))

  // Nothing below: treat the selection itself as the mod so the run still reports something
  if (subFolders.length === 0) {
    return { mods: [{ id: path.basename(rootPath), path: rootPath }], single: true }
  }

  return { mods: subFolders, single: false }
}

/** Set by the worker when the user asks to stop, checked between units of work */
export const cancellation = { requested: false }

/** What a mod needs, computed once and reused by the scan and the conversion */
interface ModPlan {
  name: string
  supportedVersion?: string
  localisationFiles: number
  sourceFiles: number
  /** Files to create, per target language */
  jobs: Record<string, CreationJob[]>
  errors: string[]
}

/**
 * Work out what is missing in a mod, without touching the disk
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param packed - Also compute the paths used inside a translation mod
 * @returns The plan for that mod
 */
const planMod = async (
  mod: ModFolder,
  request: Request,
  translateKey: string,
  packed: boolean
): Promise<ModPlan> => {
  const { sourceLanguage, targetLanguages } = request
  const errors: string[] = []
  const jobs: Record<string, CreationJob[]> = {}

  const descriptor = await readDescriptor(mod.path)
  const plan: ModPlan = {
    name: descriptor.name ?? mod.id,
    supportedVersion: descriptor.supportedVersion,
    localisationFiles: 0,
    sourceFiles: 0,
    jobs,
    errors
  }

  const allFiles = await listTradFiles(mod.path, translateKey, false, errors)
  plan.localisationFiles = allFiles.length
  if (allFiles.length === 0) return plan

  const existingFiles = new Set(allFiles.map(pathKey))
  const sourceFiles = allFiles
    .map((file) => parseLocalisationFile(file, translateKey))
    .filter((file): file is LocalisationFile => file !== null)
    .filter((file) => isSourceLanguageFile(file, sourceLanguage))
  plan.sourceFiles = sourceFiles.length

  for (const language of targetLanguages) {
    if (language === sourceLanguage) continue

    const seen = new Set<string>()
    const languageJobs: CreationJob[] = []

    for (const file of sourceFiles) {
      const target = getTargetFile(file, sourceLanguage, language)
      const key = pathKey(target)
      // Two source files can map onto the same target, keep the first one only
      if (key === pathKey(file.path) || existingFiles.has(key) || seen.has(key)) continue
      seen.add(key)
      languageJobs.push({
        source: file.path,
        target,
        packed: packed ? getTranslationModPath(file, target, sourceLanguage) : []
      })
    }

    if (languageJobs.length > 0) jobs[language] = languageJobs
  }

  return plan
}

/**
 * Count the lines a translator would have to handle
 * @param jobs - The planned files, per language
 * @returns The number of translatable lines
 */
const countTranslatableLines = async (jobs: Record<string, CreationJob[]>): Promise<number> => {
  const perFile = new Map<string, number>()
  let total = 0

  for (const language of Object.keys(jobs)) {
    for (const job of jobs[language]) {
      let count = perFile.get(job.source)
      if (count === undefined) {
        try {
          const content = await fs.readFile(job.source, 'utf8')
          count = parseLocFile(content).filter(
            (line) => line.entry && isTranslatable(line.entry.value)
          ).length
        } catch {
          count = 0
        }
        perFile.set(job.source, count)
      }
      total += count
    }
  }

  return total
}

/**
 * Report what a mod is missing, creating nothing
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param countLines - Read the source files to estimate the translation workload
 * @returns The scan result
 */
const scanMod = async (
  mod: ModFolder,
  request: Request,
  translateKey: string,
  countLines: boolean
): Promise<ScannedMod> => {
  const plan = await planMod(mod, request, translateKey, false)

  const missing: Record<string, number> = {}
  let missingFiles = 0
  for (const language of Object.keys(plan.jobs)) {
    missing[language] = plan.jobs[language].length
    missingFiles += plan.jobs[language].length
  }

  return {
    id: mod.id,
    name: plan.name,
    path: mod.path,
    localisationFiles: plan.localisationFiles,
    sourceFiles: plan.sourceFiles,
    missing,
    missingFiles,
    missingLines: countLines && missingFiles > 0 ? await countTranslatableLines(plan.jobs) : 0,
    supportedVersion: plan.supportedVersion,
    errors: plan.errors
  }
}

/**
 * Build the content of one target file, translating its values when asked to
 * @param job - The file to create
 * @param sourceLanguage - The source language key
 * @param language - The target language key
 * @param translations - Known translations, missing entries stay in the source language
 * @returns The file content
 */
const buildTargetContent = async (
  job: CreationJob,
  sourceLanguage: string,
  language: string,
  translations?: Map<string, string>
): Promise<string> => {
  const sourceContent = await fs.readFile(job.source, 'utf8')
  const retagged = sourceContent.replaceAll(`l_${sourceLanguage}`, `l_${language}`)
  if (!translations) return retagged

  const lines = parseLocFile(retagged).map((line) => {
    const translated = line.entry && translations.get(line.entry.value)
    return translated && line.entry
      ? { ...line, entry: { ...line.entry, value: translated } }
      : line
  })

  return serializeLocFile(lines)
}

/**
 * Create the missing translation files of a single mod
 * Every failure is captured in the result, one broken mod never stops the others
 * @param mod - The mod folder
 * @param request - The conversion request
 * @param translateKey - The game's folder translate key
 * @param translationMod - Set when everything goes into one generated mod
 * @param engine - Set when the values must be translated, not just copied
 * @param languageNames - Game language key to its English name, used in the prompt
 * @returns The mod result
 */
const processMod = async (
  mod: ModFolder,
  request: Request,
  translateKey: string,
  translationMod?: TranslationMod,
  engine?: TranslationEngine,
  languageNames: Record<string, string> = {}
): Promise<ModResult> => {
  const { sourceLanguage, mode, outputPath } = request
  const outputDir = mode === ConvertMode.EXTRACT_TO_FOLDER ? outputPath : undefined

  const created: Record<string, string[]> = {}
  const plan = await planMod(mod, request, translateKey, Boolean(translationMod))
  const result: ModResult = {
    id: mod.id,
    name: plan.name,
    path: mod.path,
    localisationFiles: plan.localisationFiles,
    sourceFiles: plan.sourceFiles,
    createdCount: 0,
    skippedCount: 0,
    failedCount: 0,
    created,
    truncated: 0,
    supportedVersion: plan.supportedVersion,
    errors: plan.errors
  }

  const namespace = translationMod ? getModNamespace(mod, plan.name) : ''

  for (const language of Object.keys(plan.jobs)) {
    if (cancellation.requested) break
    const jobs = plan.jobs[language]

    let translations: Map<string, string> | undefined
    if (engine) {
      const values: string[] = []
      for (const job of jobs) {
        try {
          const content = await fs.readFile(job.source, 'utf8')
          for (const line of parseLocFile(content)) {
            if (line.entry && isTranslatable(line.entry.value)) values.push(line.entry.value)
          }
        } catch {
          // The write below reports the unreadable file
        }
      }

      try {
        translations = await engine.translate(values, language, languageNames[language] ?? language)
      } catch (error) {
        // Backend down: fall back to copying, the run keeps its meaning
        plan.errors.push(`${language} : ${(error as Error).message}`)
        translations = new Map()
      }
    }

    if (cancellation.requested) break

    const languageFiles: string[] = []

    await Promise.all(
      jobs.map(async (job) => {
        try {
          const targetContent = await buildTargetContent(
            job,
            sourceLanguage,
            language,
            translations
          )

          let destination = job.target
          if (translationMod) {
            // Namespaced per source mod, two mods shipping the same file name never collide
            destination = path.join(
              translationMod.path,
              translateKey,
              language,
              namespace,
              ...job.packed
            )
          } else if (outputDir) {
            destination = path.join(outputDir, mod.id, path.relative(mod.path, job.target))
          }

          await fs.mkdir(path.dirname(destination), { recursive: true })
          // wx: never overwrite an existing translation, even outside the scanned folder
          await fs.writeFile(destination, targetContent, { encoding: 'utf8', flag: 'wx' })
          languageFiles.push(destination)
        } catch (error) {
          if ((error as NodeJS.ErrnoException).code === 'EEXIST') {
            result.skippedCount++
          } else {
            result.failedCount++
            plan.errors.push(`${job.target} : ${(error as Error).message}`)
          }
        }
      })
    )

    if (languageFiles.length > 0) {
      result.createdCount += languageFiles.length
      created[language] = languageFiles.slice(0, MAX_LISTED_FILES_PER_MOD)
      result.truncated += languageFiles.length - created[language].length
    }
  }

  return result
}

/**
 * Game language key to its English name, the translator prompt needs a real language name
 * @param game - The game key
 * @returns braz_por to Portuguese, simp_chinese to Chinese, ...
 */
const getLanguageNames = (game: string): Record<string, string> => {
  const names: Record<string, string> = {}
  const languageKeys = GAMES[game].languageKeys as Record<string, string>
  for (const [code, key] of Object.entries(languageKeys)) {
    names[key] = LANGUAGES[code as keyof typeof LANGUAGES] ?? key
  }
  return names
}

/**
 * Report what every mod is missing, without writing anything
 * @param request - The scan request
 * @param workerPort - The worker port, used for progress
 * @returns The scan result
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const launchScan = async (request: Request, workerPort: any): Promise<ScanOutput> => {
  const translateKey = GAMES[request.game].translateKey
  const countLines = Boolean(request.translate?.enabled)

  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.SCANNING_FILES
  })

  const { mods } = await discoverMods(request.path, translateKey)

  let done = 0
  const results = await mapWithConcurrency(mods, MOD_CONCURRENCY, async (mod) => {
    const result = await scanMod(mod, request, translateKey, countLines)
    done++
    workerPort.postMessage({
      type: ConversionStatusType.PROGRESS,
      current: done,
      total: mods.length,
      modName: result.name
    })
    return result
  })

  const totals = results.reduce(
    (acc, mod) => ({
      mods: acc.mods + 1,
      missingFiles: acc.missingFiles + mod.missingFiles,
      missingLines: acc.missingLines + mod.missingLines
    }),
    { mods: 0, missingFiles: 0, missingLines: 0 }
  )

  // Mods needing work first, the rest keeps the list readable
  const sorted = [...results].sort(
    (a, b) => b.missingFiles - a.missingFiles || a.name.localeCompare(b.name)
  )

  return { mods: sorted, totals }
}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const launchTranslation = async (request: Request, workerPort: any): Promise<ConversionOutput> => {
  const addLog = (message: string, values?: LogValues): void => {
    workerPort.postMessage({
      type: ConversionStatusType.LOG,
      ts: Date.now(),
      message,
      values
    })
  }

  const { path: rootPath, game, mode, modName, documentsPath, userDataPath, selectedMods } = request
  const translateKey = GAMES[game].translateKey

  let translationMod: TranslationMod | undefined
  let gameModsDir = ''
  if (mode === ConvertMode.CREATE_TRANSLATION_MOD) {
    if (!documentsPath) throw new Error('Documents folder could not be resolved')
    gameModsDir = path.join(documentsPath, 'Paradox Interactive', GAMES[game].userFolder, 'mod')

    const name = modName?.trim() || DEFAULT_MOD_NAME
    translationMod = {
      name,
      folder: sanitizeFolderName(name, 48) || DEFAULT_MOD_FOLDER,
      path: '',
      // Replaced once the source mods have been read
      supportedVersion: '*'
    }
    translationMod.path = path.join(gameModsDir, translationMod.folder)
  }

  addLog(ConversionLogMessage.STARTING)
  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.SCANNING_FILES
  })

  const discovered = await discoverMods(rootPath, translateKey)
  // The user ticked the mods to handle in the scan list, an empty selection means everything
  const mods = selectedMods?.length
    ? discovered.mods.filter((mod) => selectedMods.includes(mod.id))
    : discovered.mods
  addLog(discovered.single ? ConversionLogMessage.SINGLE_MOD : ConversionLogMessage.MODS_FOUND, {
    count: mods.length
  })

  let engine: TranslationEngine | undefined
  let memory: TranslationMemory | undefined
  let lastProgress = { current: 0, total: mods.length, modName: '' }

  if (request.translate?.enabled) {
    if (!userDataPath) throw new Error('Translation memory folder could not be resolved')
    memory = new TranslationMemory(path.join(userDataPath, 'translation-memory'))
    engine = new TranslationEngine(request.translate, memory, (translation) => {
      workerPort.postMessage({
        type: ConversionStatusType.PROGRESS,
        ...lastProgress,
        translation
      })
    })
    addLog(ConversionLogMessage.TRANSLATING, {
      provider: request.translate.provider,
      model: request.translate.model
    })
  }

  workerPort.postMessage({
    type: ConversionStatusType.STATUS,
    status: ConversionStatus.PROCESSING_MODS
  })

  const languageNames = getLanguageNames(game)
  // A translation backend is the bottleneck, holding fewer mods in flight keeps memory low
  const concurrency = engine ? 2 : MOD_CONCURRENCY

  let done = 0
  const results = await mapWithConcurrency(mods, concurrency, async (mod) => {
    const result = await processMod(
      mod,
      request,
      translateKey,
      translationMod,
      engine,
      languageNames
    )
    done++
    lastProgress = { current: done, total: mods.length, modName: result.name }
    workerPort.postMessage({
      type: ConversionStatusType.PROGRESS,
      ...lastProgress,
      translation: engine?.getCounters()
    })
    return result
  })

  await memory?.flush()

  const totals = results.reduce(
    (acc, mod) => ({
      mods: acc.mods + 1,
      modsWithFiles: acc.modsWithFiles + (mod.createdCount > 0 ? 1 : 0),
      created: acc.created + mod.createdCount,
      skipped: acc.skipped + mod.skippedCount,
      failed: acc.failed + mod.failedCount,
      errors: acc.errors + mod.errors.length
    }),
    { mods: 0, modsWithFiles: 0, created: 0, skipped: 0, failed: 0, errors: 0 }
  )

  addLog(ConversionLogMessage.SUMMARY, {
    created: totals.created,
    mods: totals.modsWithFiles,
    failed: totals.failed
  })

  if (translationMod && totals.created > 0) {
    translationMod.supportedVersion = pickSupportedVersion(results)
    await fs.mkdir(translationMod.path, { recursive: true })
    // Both files are needed: the launcher reads mod/<folder>.mod, the game reads the inner one
    await fs.writeFile(
      path.join(gameModsDir, `${translationMod.folder}.mod`),
      buildDescriptor(translationMod, true),
      'utf8'
    )
    await fs.writeFile(
      path.join(translationMod.path, 'descriptor.mod'),
      buildDescriptor(translationMod, false),
      'utf8'
    )
    addLog(ConversionLogMessage.MOD_CREATED, { name: translationMod.name })
  }

  addLog(ConversionLogMessage.DONE)

  // Mods that produced something first, then the ones that need attention
  const sortedMods = [...results].sort(
    (a, b) =>
      b.createdCount - a.createdCount ||
      b.errors.length - a.errors.length ||
      a.name.localeCompare(b.name)
  )

  return {
    mods: sortedMods,
    translationMod,
    translation: engine?.getCounters(),
    cancelled: cancellation.requested,
    totals
  }
}

/**
 * Entry point of the worker: scan the mods or actually create the files
 * @param request - What to do
 * @param workerPort - The worker port, used for logs and progress
 * @returns The scan or conversion result
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const run = async (request: Request, workerPort: any): Promise<ScanOutput | ConversionOutput> =>
  request.action === WorkerAction.SCAN
    ? launchScan(request, workerPort)
    : launchTranslation(request, workerPort)

export default run
