import { describe, expect, it } from 'vitest'

import { parseVdf } from '../src/vdf.js'
import type { VdfNode, VdfValue } from '../src/vdf.js'

const isVdfNode = (value: VdfValue | undefined): value is VdfNode =>
  typeof value === 'object' && value !== null

const readNode = (node: VdfNode, key: string): VdfNode => {
  const value = node[key]
  if (!isVdfNode(value)) {
    throw new Error(`expected "${key}" to be a VdfNode`)
  }
  return value
}

const readString = (node: VdfNode, key: string): string => {
  const value = node[key]
  if (typeof value !== 'string') {
    throw new Error(`expected "${key}" to be a string`)
  }
  return value
}

describe('parseVdf', () => {
  it('parses the recent libraryfolders.vdf format with nested numbered objects', () => {
    const content = [
      '"libraryfolders"',
      '{',
      '\t"0"',
      '\t{',
      '\t\t"path"\t\t"C:\\\\Program Files (x86)\\\\Steam"',
      '\t\t"label"\t\t""',
      '\t\t"contentid"\t\t"1234567890"',
      '\t\t"totalsize"\t\t"0"',
      '\t\t"apps"',
      '\t\t{',
      '\t\t\t"281990"\t\t"48945609"',
      '\t\t}',
      '\t}',
      '\t"1"',
      '\t{',
      '\t\t"path"\t\t"D:\\\\SteamLibrary"',
      '\t\t"mounted"\t\t"1"',
      '\t}',
      '}'
    ].join('\n')

    const root = parseVdf(content)
    const libraryFolders = readNode(root, 'libraryfolders')
    const folder0 = readNode(libraryFolders, '0')
    const folder1 = readNode(libraryFolders, '1')
    const apps = readNode(folder0, 'apps')

    expect(readString(folder0, 'path')).toBe('C:\\Program Files (x86)\\Steam')
    expect(readString(folder1, 'path')).toBe('D:\\SteamLibrary')
    expect(readString(apps, '281990')).toBe('48945609')
  })

  it('parses the old libraryfolders.vdf format where numeric keys map directly to paths', () => {
    const content = [
      '"LibraryFolders"',
      '{',
      '\t"TimeNextStatsReport"\t\t"1700000000"',
      '\t"ContentStatsID"\t\t"-1234567890"',
      '\t"1"\t\t"D:\\\\SteamLibrary"',
      '\t"2"\t\t"E:\\\\Games\\\\Steam"',
      '}'
    ].join('\n')

    const root = parseVdf(content)
    const libraryFolders = readNode(root, 'LibraryFolders')

    expect(readString(libraryFolders, '1')).toBe('D:\\SteamLibrary')
    expect(readString(libraryFolders, '2')).toBe('E:\\Games\\Steam')
  })

  it('parses the deeply nested config.vdf format', () => {
    const content = [
      '"InstallConfigStore"',
      '{',
      '\t"Software"',
      '\t{',
      '\t\t"Valve"',
      '\t\t{',
      '\t\t\t"Steam"',
      '\t\t\t{',
      '\t\t\t\t"BaseInstallFolder_1"\t\t"D:\\\\SteamLibrary"',
      '\t\t\t\t"BaseInstallFolder_2"\t\t"E:\\\\Games\\\\Steam"',
      '\t\t\t}',
      '\t\t}',
      '\t}',
      '}'
    ].join('\n')

    const root = parseVdf(content)
    const steam = readNode(
      readNode(readNode(readNode(root, 'InstallConfigStore'), 'Software'), 'Valve'),
      'Steam'
    )

    expect(readString(steam, 'BaseInstallFolder_1')).toBe('D:\\SteamLibrary')
    expect(readString(steam, 'BaseInstallFolder_2')).toBe('E:\\Games\\Steam')
  })

  it('parses an appmanifest .acf file', () => {
    const content = [
      '"AppState"',
      '{',
      '\t"appid"\t\t"281990"',
      '\t"name"\t\t"Stellaris"',
      '\t"installdir"\t\t"Stellaris"',
      '\t"StateFlags"\t\t"4"',
      '}'
    ].join('\n')

    const root = parseVdf(content)
    const appState = readNode(root, 'AppState')

    expect(readString(appState, 'installdir')).toBe('Stellaris')
    expect(readString(appState, 'name')).toBe('Stellaris')
  })

  it('unescapes doubled backslashes and quotes in a Windows path', () => {
    const content = '"path"\t\t"D:\\\\SteamLibrary\\\\common\\\\Some \\"Game\\""'

    const root = parseVdf(content)

    expect(readString(root, 'path')).toBe('D:\\SteamLibrary\\common\\Some "Game"')
  })

  it('ignores comment lines starting with //', () => {
    const content = [
      '// this whole file is generated by Steam',
      '"AppState"',
      '{',
      '\t// appid comment',
      '\t"appid"\t\t"281990"',
      '}'
    ].join('\n')

    const root = parseVdf(content)
    const appState = readNode(root, 'AppState')

    expect(readString(appState, 'appid')).toBe('281990')
  })

  it('returns an empty node when nesting exceeds the max depth', () => {
    const depth = 40
    let content = ''
    for (let i = 0; i < depth; i += 1) {
      content += `"k${i}"\n{\n`
    }
    content += '}'.repeat(depth)

    expect(parseVdf(content)).toEqual({})
  })

  it('returns an empty node when content exceeds the max size', () => {
    const content = '"a"'.repeat(100_000)

    expect(parseVdf(content)).toEqual({})
  })

  it('returns an empty node for an empty string', () => {
    expect(parseVdf('')).toEqual({})
  })

  it('does not throw on content truncated in the middle of an object', () => {
    const content = ['"AppState"', '{', '\t"appid"\t\t"281990"', '\t"name"\t\t"Stel'].join('\n')

    const root = parseVdf(content)
    const appState = readNode(root, 'AppState')

    expect(readString(appState, 'appid')).toBe('281990')
    expect(readString(appState, 'name')).toBe('Stel')
  })

  it('does not throw on an unterminated quote', () => {
    const content = '"key"\t\t"value'

    const root = parseVdf(content)

    expect(readString(root, 'key')).toBe('value')
  })

  it('stores a "__proto__" key as an own property instead of polluting the node prototype', () => {
    const content = '"__proto__"\n{\n\t"polluted"\t\t"yes"\n}'

    const root = parseVdf(content)

    expect(Object.keys(root)).toEqual(['__proto__'])
    expect(Object.getPrototypeOf(root)).toBeNull()
    expect(root['polluted']).toBeUndefined()
    expect(readNode(root, '__proto__')).toEqual({ polluted: 'yes' })
  })
})
